#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(dead_code)]

use std::ffi::c_void;

// --- Windows Base Types ---
pub type HANDLE = *mut c_void;
pub type BOOL = i32;
pub type WORD = u16;
pub type DWORD = u32;
pub type BYTE = u8;
pub type WCHAR = u16;
pub type IntPtr = isize;
pub type UIntPtr = usize;
pub type COLORREF = u32;
pub type LPSECURITY_ATTRIBUTES = *mut c_void;

pub const TRUE: BOOL = 1;
pub const FALSE: BOOL = 0;

#[repr(C)]
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct RECT {
    pub left: i32,
    pub top: i32,
    pub right: i32,
    pub bottom: i32,
}

#[repr(C)]
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct COORD {
    pub X: i16,
    pub Y: i16,
}

#[repr(C)]
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct FILETIME {
    pub dwLowDateTime: u32,
    pub dwHighDateTime: u32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct INPUT_RECORD {
    pub EventType: WORD,
    pub Event: [u8; 18],
}

impl Default for INPUT_RECORD {
    fn default() -> Self {
        Self { EventType: 0, Event: [0; 18] }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct GUID {
    pub Data1: u32,
    pub Data2: u16,
    pub Data3: u16,
    pub Data4: [u8; 8],
}
pub type UUID = GUID;

// --- FAR Constants & Macros ---
pub const CP_UTF16LE: UIntPtr = 1200;
pub const CP_UTF16BE: UIntPtr = 1201;
pub const CP_UNICODE: UIntPtr = CP_UTF16LE;
pub const CP_REVERSEBOM: UIntPtr = CP_UTF16BE;
pub const CP_DEFAULT: UIntPtr = !0;
pub const CP_REDETECT: UIntPtr = !1;

pub const INDEXMASK: u64 = 0x000000ff;
pub const COLORMASK: u64 = 0x00ffffff;
pub const ALPHAMASK: u64 = 0xff000000;

pub fn INDEXVALUE(x: u64) -> u8 { (x & INDEXMASK) as u8 }
pub fn COLORVALUE(x: u64) -> u32 { (x & COLORMASK) as u32 }
pub fn ALPHAVALUE(x: u64) -> u8 { ((x & ALPHAMASK) >> 24) as u8 }
pub fn IS_OPAQUE(x: u64) -> bool { (x & ALPHAMASK) == ALPHAMASK }
pub fn IS_TRANSPARENT(x: u64) -> bool { (x & ALPHAMASK) == 0 }
pub fn MAKE_OPAQUE(x: u64) -> u64 { x | ALPHAMASK }
pub fn MAKE_TRANSPARENT(x: u64) -> u64 { x & COLORMASK }

pub const PANEL_NONE: HANDLE = -1isize as HANDLE;
pub const PANEL_ACTIVE: HANDLE = -1isize as HANDLE;
pub const PANEL_PASSIVE: HANDLE = -2isize as HANDLE;
pub const PANEL_STOP: HANDLE = -1isize as HANDLE;

// --- FAR Enums ---
pub type UNDERLINE_STYLE = i32;
pub const UNDERLINE_NONE: UNDERLINE_STYLE = 0;
pub const UNDERLINE_SINGLE: UNDERLINE_STYLE = 1;
pub const UNDERLINE_DOUBLE: UNDERLINE_STYLE = 2;
pub const UNDERLINE_CURLY: UNDERLINE_STYLE = 3;
pub const UNDERLINE_DOT: UNDERLINE_STYLE = 4;
pub const UNDERLINE_DASH: UNDERLINE_STYLE = 5;

pub type FARDIALOGITEMTYPES = i32;
pub const DI_TEXT: FARDIALOGITEMTYPES = 0;
pub const DI_VTEXT: FARDIALOGITEMTYPES = 1;
pub const DI_SINGLEBOX: FARDIALOGITEMTYPES = 2;
pub const DI_DOUBLEBOX: FARDIALOGITEMTYPES = 3;
pub const DI_EDIT: FARDIALOGITEMTYPES = 4;
pub const DI_PSWEDIT: FARDIALOGITEMTYPES = 5;
pub const DI_FIXEDIT: FARDIALOGITEMTYPES = 6;
pub const DI_BUTTON: FARDIALOGITEMTYPES = 7;
pub const DI_CHECKBOX: FARDIALOGITEMTYPES = 8;
pub const DI_RADIOBUTTON: FARDIALOGITEMTYPES = 9;
pub const DI_COMBOBOX: FARDIALOGITEMTYPES = 10;
pub const DI_LISTBOX: FARDIALOGITEMTYPES = 11;
pub const DI_USERCONTROL: FARDIALOGITEMTYPES = 255;

pub type FARMESSAGE = i32;
pub const DM_FIRST: FARMESSAGE = 0;
pub const DM_CLOSE: FARMESSAGE = 1;
pub const DM_ENABLE: FARMESSAGE = 2;
pub const DM_ENABLEREDRAW: FARMESSAGE = 3;
pub const DM_GETDLGDATA: FARMESSAGE = 4;
pub const DM_GETDLGITEM: FARMESSAGE = 5;
pub const DM_GETDLGRECT: FARMESSAGE = 6;
pub const DM_GETTEXT: FARMESSAGE = 7;
pub const DM_KEY: FARMESSAGE = 9;
pub const DM_MOVEDIALOG: FARMESSAGE = 10;
pub const DM_SETDLGDATA: FARMESSAGE = 11;
pub const DM_SETDLGITEM: FARMESSAGE = 12;
pub const DM_SETFOCUS: FARMESSAGE = 13;
pub const DM_REDRAW: FARMESSAGE = 14;
pub const DM_SETTEXT: FARMESSAGE = 15;
pub const DM_SETMAXTEXTLENGTH: FARMESSAGE = 16;
pub const DM_SHOWDIALOG: FARMESSAGE = 17;
pub const DM_GETFOCUS: FARMESSAGE = 18;
pub const DM_GETCURSORPOS: FARMESSAGE = 19;
pub const DM_SETCURSORPOS: FARMESSAGE = 20;
pub const DM_SETTEXTPTR: FARMESSAGE = 22;
pub const DM_SHOWITEM: FARMESSAGE = 23;
pub const DM_ADDHISTORY: FARMESSAGE = 24;
pub const DM_GETCHECK: FARMESSAGE = 25;
pub const DM_SETCHECK: FARMESSAGE = 26;
pub const DM_SET3STATE: FARMESSAGE = 27;
pub const DM_LISTSORT: FARMESSAGE = 28;
pub const DM_LISTGETITEM: FARMESSAGE = 29;
pub const DM_LISTGETCURPOS: FARMESSAGE = 30;
pub const DM_LISTSETCURPOS: FARMESSAGE = 31;
pub const DM_LISTDELETE: FARMESSAGE = 32;
pub const DM_LISTADD: FARMESSAGE = 33;
pub const DM_LISTADDSTR: FARMESSAGE = 34;
pub const DM_LISTUPDATE: FARMESSAGE = 35;
pub const DM_LISTINSERT: FARMESSAGE = 36;
pub const DM_LISTFINDSTRING: FARMESSAGE = 37;
pub const DM_LISTINFO: FARMESSAGE = 38;
pub const DM_LISTGETDATA: FARMESSAGE = 39;
pub const DM_LISTSETDATA: FARMESSAGE = 40;
pub const DM_LISTSETTITLES: FARMESSAGE = 41;
pub const DM_LISTGETTITLES: FARMESSAGE = 42;
pub const DM_RESIZEDIALOG: FARMESSAGE = 43;
pub const DM_SETITEMPOSITION: FARMESSAGE = 44;
pub const DM_GETDROPDOWNOPENED: FARMESSAGE = 45;
pub const DM_SETDROPDOWNOPENED: FARMESSAGE = 46;
pub const DM_SETHISTORY: FARMESSAGE = 47;
pub const DM_GETITEMPOSITION: FARMESSAGE = 48;
pub const DM_SETINPUTNOTIFY: FARMESSAGE = 49;
pub const DM_SETMOUSEEVENTNOTIFY: FARMESSAGE = 49;
pub const DM_EDITUNCHANGEDFLAG: FARMESSAGE = 50;
pub const DM_GETITEMDATA: FARMESSAGE = 51;
pub const DM_SETITEMDATA: FARMESSAGE = 52;
pub const DM_LISTSET: FARMESSAGE = 53;
pub const DM_GETCURSORSIZE: FARMESSAGE = 54;
pub const DM_SETCURSORSIZE: FARMESSAGE = 55;
pub const DM_LISTGETDATASIZE: FARMESSAGE = 56;
pub const DM_GETSELECTION: FARMESSAGE = 57;
pub const DM_SETSELECTION: FARMESSAGE = 58;
pub const DM_GETEDITPOSITION: FARMESSAGE = 59;
pub const DM_SETEDITPOSITION: FARMESSAGE = 60;
pub const DM_SETCOMBOBOXEVENT: FARMESSAGE = 61;
pub const DM_GETCOMBOBOXEVENT: FARMESSAGE = 62;
pub const DM_GETCONSTTEXTPTR: FARMESSAGE = 63;
pub const DM_GETDLGITEMSHORT: FARMESSAGE = 64;
pub const DM_SETDLGITEMSHORT: FARMESSAGE = 65;
pub const DM_GETDIALOGINFO: FARMESSAGE = 66;
pub const DM_GETDIALOGTITLE: FARMESSAGE = 67;

pub const DN_FIRST: FARMESSAGE = 4096;
pub const DN_BTNCLICK: FARMESSAGE = 4097;
pub const DN_CTLCOLORDIALOG: FARMESSAGE = 4098;
pub const DN_CTLCOLORDLGITEM: FARMESSAGE = 4099;
pub const DN_CTLCOLORDLGLIST: FARMESSAGE = 4100;
pub const DN_DRAWDIALOG: FARMESSAGE = 4101;
pub const DN_DRAWDLGITEM: FARMESSAGE = 4102;
pub const DN_EDITCHANGE: FARMESSAGE = 4103;
pub const DN_GOTFOCUS: FARMESSAGE = 4105;
pub const DN_HELP: FARMESSAGE = 4106;
pub const DN_HOTKEY: FARMESSAGE = 4107;
pub const DN_INITDIALOG: FARMESSAGE = 4108;
pub const DN_KILLFOCUS: FARMESSAGE = 4109;
pub const DN_LISTCHANGE: FARMESSAGE = 4110;
pub const DN_DRAGGED: FARMESSAGE = 4111;
pub const DN_RESIZECONSOLE: FARMESSAGE = 4112;
pub const DN_DRAWDIALOGDONE: FARMESSAGE = 4113;
pub const DN_LISTHOTKEY: FARMESSAGE = 4114;
pub const DN_INPUT: FARMESSAGE = 4115;
pub const DN_CONTROLINPUT: FARMESSAGE = 4116;
pub const DN_CLOSE: FARMESSAGE = 4117;
pub const DN_GETVALUE: FARMESSAGE = 4118;
pub const DN_DROPDOWNOPENED: FARMESSAGE = 4119;
pub const DN_DRAWDLGITEMDONE: FARMESSAGE = 4120;

pub const DM_USER: FARMESSAGE = 0x4000;

pub type FARCHECKEDSTATE = i32;
pub const BSTATE_UNCHECKED: FARCHECKEDSTATE = 0;
pub const BSTATE_CHECKED: FARCHECKEDSTATE = 1;
pub const BSTATE_3STATE: FARCHECKEDSTATE = 2;
pub const BSTATE_TOGGLE: FARCHECKEDSTATE = 3;

pub type FARCOMBOBOXEVENTTYPE = i32;
pub const CBET_KEY: FARCOMBOBOXEVENTTYPE = 0x00000001;
pub const CBET_MOUSE: FARCOMBOBOXEVENTTYPE = 0x00000002;

pub type PANELINFOTYPE = i32;
pub const PTYPE_FILEPANEL: PANELINFOTYPE = 0;
pub const PTYPE_TREEPANEL: PANELINFOTYPE = 1;
pub const PTYPE_QVIEWPANEL: PANELINFOTYPE = 2;
pub const PTYPE_INFOPANEL: PANELINFOTYPE = 3;

pub type OPENPANELINFO_SORTMODES = i32;
pub const SM_DEFAULT: OPENPANELINFO_SORTMODES = 0;
pub const SM_UNSORTED: OPENPANELINFO_SORTMODES = 1;
pub const SM_NAME: OPENPANELINFO_SORTMODES = 2;
pub const SM_FULLNAME: OPENPANELINFO_SORTMODES = SM_NAME;
pub const SM_EXT: OPENPANELINFO_SORTMODES = 3;
pub const SM_MTIME: OPENPANELINFO_SORTMODES = 4;
pub const SM_CTIME: OPENPANELINFO_SORTMODES = 5;
pub const SM_ATIME: OPENPANELINFO_SORTMODES = 6;
pub const SM_SIZE: OPENPANELINFO_SORTMODES = 7;
pub const SM_DESCR: OPENPANELINFO_SORTMODES = 8;
pub const SM_OWNER: OPENPANELINFO_SORTMODES = 9;
pub const SM_COMPRESSEDSIZE: OPENPANELINFO_SORTMODES = 10;
pub const SM_NUMLINKS: OPENPANELINFO_SORTMODES = 11;
pub const SM_NUMSTREAMS: OPENPANELINFO_SORTMODES = 12;
pub const SM_STREAMSSIZE: OPENPANELINFO_SORTMODES = 13;
pub const SM_NAMEONLY: OPENPANELINFO_SORTMODES = 14;
pub const SM_CHTIME: OPENPANELINFO_SORTMODES = 15;
pub const SM_USER: OPENPANELINFO_SORTMODES = 100000;

pub type FILE_CONTROL_COMMANDS = i32;
pub const FCTL_CLOSEPANEL: FILE_CONTROL_COMMANDS = 0;
pub const FCTL_GETPANELINFO: FILE_CONTROL_COMMANDS = 1;
pub const FCTL_UPDATEPANEL: FILE_CONTROL_COMMANDS = 2;
pub const FCTL_REDRAWPANEL: FILE_CONTROL_COMMANDS = 3;
pub const FCTL_GETCMDLINE: FILE_CONTROL_COMMANDS = 4;
pub const FCTL_SETCMDLINE: FILE_CONTROL_COMMANDS = 5;
pub const FCTL_SETSELECTION: FILE_CONTROL_COMMANDS = 6;
pub const FCTL_SETVIEWMODE: FILE_CONTROL_COMMANDS = 7;
pub const FCTL_INSERTCMDLINE: FILE_CONTROL_COMMANDS = 8;
pub const FCTL_SETUSERSCREEN: FILE_CONTROL_COMMANDS = 9;
pub const FCTL_SETPANELDIRECTORY: FILE_CONTROL_COMMANDS = 10;
pub const FCTL_SETCMDLINEPOS: FILE_CONTROL_COMMANDS = 11;
pub const FCTL_GETCMDLINEPOS: FILE_CONTROL_COMMANDS = 12;
pub const FCTL_SETSORTMODE: FILE_CONTROL_COMMANDS = 13;
pub const FCTL_SETSORTORDER: FILE_CONTROL_COMMANDS = 14;
pub const FCTL_SETCMDLINESELECTION: FILE_CONTROL_COMMANDS = 15;
pub const FCTL_GETCMDLINESELECTION: FILE_CONTROL_COMMANDS = 16;
pub const FCTL_CHECKPANELSEXIST: FILE_CONTROL_COMMANDS = 17;
pub const FCTL_GETUSERSCREEN: FILE_CONTROL_COMMANDS = 19;
pub const FCTL_ISACTIVEPANEL: FILE_CONTROL_COMMANDS = 20;
pub const FCTL_GETPANELITEM: FILE_CONTROL_COMMANDS = 21;
pub const FCTL_GETSELECTEDPANELITEM: FILE_CONTROL_COMMANDS = 22;
pub const FCTL_GETCURRENTPANELITEM: FILE_CONTROL_COMMANDS = 23;
pub const FCTL_GETPANELDIRECTORY: FILE_CONTROL_COMMANDS = 24;
pub const FCTL_GETCOLUMNTYPES: FILE_CONTROL_COMMANDS = 25;
pub const FCTL_GETCOLUMNWIDTHS: FILE_CONTROL_COMMANDS = 26;
pub const FCTL_BEGINSELECTION: FILE_CONTROL_COMMANDS = 27;
pub const FCTL_ENDSELECTION: FILE_CONTROL_COMMANDS = 28;
pub const FCTL_CLEARSELECTION: FILE_CONTROL_COMMANDS = 29;
pub const FCTL_SETDIRECTORIESFIRST: FILE_CONTROL_COMMANDS = 30;
pub const FCTL_GETPANELFORMAT: FILE_CONTROL_COMMANDS = 31;
pub const FCTL_GETPANELHOSTFILE: FILE_CONTROL_COMMANDS = 32;
pub const FCTL_GETPANELPREFIX: FILE_CONTROL_COMMANDS = 34;
pub const FCTL_SETACTIVEPANEL: FILE_CONTROL_COMMANDS = 35;

pub type OPENFROM = i32;
pub const OPEN_LEFTDISKMENU: OPENFROM = 0;
pub const OPEN_PLUGINSMENU: OPENFROM = 1;
pub const OPEN_FINDLIST: OPENFROM = 2;
pub const OPEN_SHORTCUT: OPENFROM = 3;
pub const OPEN_COMMANDLINE: OPENFROM = 4;
pub const OPEN_EDITOR: OPENFROM = 5;
pub const OPEN_VIEWER: OPENFROM = 6;
pub const OPEN_FILEPANEL: OPENFROM = 7;
pub const OPEN_DIALOG: OPENFROM = 8;
pub const OPEN_ANALYSE: OPENFROM = 9;
pub const OPEN_RIGHTDISKMENU: OPENFROM = 10;
pub const OPEN_FROMMACRO: OPENFROM = 11;
pub const OPEN_LUAMACRO: OPENFROM = 100;

pub type VERSION_STAGE = i32;
pub const VS_RELEASE: VERSION_STAGE = 0;
pub const VS_ALPHA: VERSION_STAGE = 1;
pub const VS_BETA: VERSION_STAGE = 2;
pub const VS_RC: VERSION_STAGE = 3;
pub const VS_SPECIAL: VERSION_STAGE = 4;
pub const VS_PRIVATE: VERSION_STAGE = 5;

pub type WINDOWINFO_TYPE = i32;
pub const WTYPE_UNKNOWN: WINDOWINFO_TYPE = -1;
pub const WTYPE_DESKTOP: WINDOWINFO_TYPE = 0;
pub const WTYPE_PANELS: WINDOWINFO_TYPE = 1;
pub const WTYPE_VIEWER: WINDOWINFO_TYPE = 2;
pub const WTYPE_EDITOR: WINDOWINFO_TYPE = 3;
pub const WTYPE_DIALOG: WINDOWINFO_TYPE = 4;
pub const WTYPE_VMENU: WINDOWINFO_TYPE = 5;
pub const WTYPE_HELP: WINDOWINFO_TYPE = 6;
pub const WTYPE_COMBOBOX: WINDOWINFO_TYPE = 7;
pub const WTYPE_GRABBER: WINDOWINFO_TYPE = 8;
pub const WTYPE_HMENU: WINDOWINFO_TYPE = 9;

pub type MACROCALLTYPE = i32;
pub const MCT_MACROPARSE: MACROCALLTYPE = 0;
pub const MCT_LOADMACROS: MACROCALLTYPE = 1;
pub const MCT_ENUMMACROS: MACROCALLTYPE = 2;
pub const MCT_WRITEMACROS: MACROCALLTYPE = 3;
pub const MCT_GETMACRO: MACROCALLTYPE = 4;
pub const MCT_RECORDEDMACRO: MACROCALLTYPE = 5;
pub const MCT_DELMACRO: MACROCALLTYPE = 6;
pub const MCT_RUNSTARTMACRO: MACROCALLTYPE = 7;
pub const MCT_EXECSTRING: MACROCALLTYPE = 8;
pub const MCT_PANELSORT: MACROCALLTYPE = 9;
pub const MCT_GETCUSTOMSORTMODES: MACROCALLTYPE = 10;
pub const MCT_ADDMACRO: MACROCALLTYPE = 11;
pub const MCT_KEYMACRO: MACROCALLTYPE = 12;
pub const MCT_CANPANELSORT: MACROCALLTYPE = 13;

pub type MACROPLUGINRETURNTYPE = i32;
pub const MPRT_NORMALFINISH: MACROPLUGINRETURNTYPE = 0;
pub const MPRT_ERRORFINISH: MACROPLUGINRETURNTYPE = 1;
pub const MPRT_ERRORPARSE: MACROPLUGINRETURNTYPE = 2;
pub const MPRT_KEYS: MACROPLUGINRETURNTYPE = 3;
pub const MPRT_PRINT: MACROPLUGINRETURNTYPE = 4;
pub const MPRT_PLUGINCALL: MACROPLUGINRETURNTYPE = 5;
pub const MPRT_PLUGINMENU: MACROPLUGINRETURNTYPE = 6;
pub const MPRT_PLUGINCONFIG: MACROPLUGINRETURNTYPE = 7;
pub const MPRT_PLUGINCOMMAND: MACROPLUGINRETURNTYPE = 8;
pub const MPRT_USERMENU: MACROPLUGINRETURNTYPE = 9;
pub const MPRT_HASNOMACRO: MACROPLUGINRETURNTYPE = 10;
pub const MPRT_FILEASSOCIATIONS: MACROPLUGINRETURNTYPE = 11;
pub const MPRT_FILEHIGHLIGHT: MACROPLUGINRETURNTYPE = 12;
pub const MPRT_FILEPANELMODES: MACROPLUGINRETURNTYPE = 13;
pub const MPRT_FOLDERSHORTCUTS: MACROPLUGINRETURNTYPE = 14;
pub const MPRT_FILEMASKGROUPS: MACROPLUGINRETURNTYPE = 15;

pub type EDITOR_EVENTS = i32;
pub const EE_READ: EDITOR_EVENTS = 0;
pub const EE_SAVE: EDITOR_EVENTS = 1;
pub const EE_REDRAW: EDITOR_EVENTS = 2;
pub const EE_CLOSE: EDITOR_EVENTS = 3;
pub const EE_GOTFOCUS: EDITOR_EVENTS = 6;
pub const EE_KILLFOCUS: EDITOR_EVENTS = 7;
pub const EE_CHANGE: EDITOR_EVENTS = 8;

pub type VIEWER_EVENTS = i32;
pub const VE_READ: VIEWER_EVENTS = 0;
pub const VE_CLOSE: VIEWER_EVENTS = 1;
pub const VE_GOTFOCUS: VIEWER_EVENTS = 6;
pub const VE_KILLFOCUS: VIEWER_EVENTS = 7;

pub type DIALOG_EVENTS = i32;
pub const DE_DLGPROCINIT: DIALOG_EVENTS = 0;
pub const DE_DEFDLGPROCINIT: DIALOG_EVENTS = 1;
pub const DE_DLGPROCEND: DIALOG_EVENTS = 2;

pub type SYNCHRO_EVENTS = i32;
pub const SE_COMMONSYNCHRO: SYNCHRO_EVENTS = 0;
pub const SE_FOLDERCHANGED: SYNCHRO_EVENTS = 1;

pub type FAR_EVENTS = i32;
pub const FE_CHANGEVIEWMODE: FAR_EVENTS = 0;
pub const FE_REDRAW: FAR_EVENTS = 1;
pub const FE_IDLE: FAR_EVENTS = 2;
pub const FE_CLOSE: FAR_EVENTS = 3;
pub const FE_BREAK: FAR_EVENTS = 4;
pub const FE_COMMAND: FAR_EVENTS = 5;
pub const FE_GOTFOCUS: FAR_EVENTS = 6;
pub const FE_KILLFOCUS: FAR_EVENTS = 7;
pub const FE_CHANGESORTPARAMS: FAR_EVENTS = 8;
pub const FE_STARTSORT: FAR_EVENTS = 9;
pub const FE_ENDSORT: FAR_EVENTS = 10;

pub type EDITOR_EXITCODE = i32;
pub const EEC_OPEN_ERROR: EDITOR_EXITCODE = 0;
pub const EEC_MODIFIED: EDITOR_EXITCODE = 1;
pub const EEC_NOT_MODIFIED: EDITOR_EXITCODE = 2;
pub const EEC_LOADING_INTERRUPTED: EDITOR_EXITCODE = 3;

pub type ADVANCED_CONTROL_COMMANDS = i32;
pub const ACTL_GETFARMANAGERVERSION: ADVANCED_CONTROL_COMMANDS = 0;
pub const ACTL_WAITKEY: ADVANCED_CONTROL_COMMANDS = 2;
pub const ACTL_GETCOLOR: ADVANCED_CONTROL_COMMANDS = 3;
pub const ACTL_GETARRAYCOLOR: ADVANCED_CONTROL_COMMANDS = 4;
pub const ACTL_GETWINDOWINFO: ADVANCED_CONTROL_COMMANDS = 6;
pub const ACTL_GETWINDOWCOUNT: ADVANCED_CONTROL_COMMANDS = 7;
pub const ACTL_SETCURRENTWINDOW: ADVANCED_CONTROL_COMMANDS = 8;
pub const ACTL_COMMIT: ADVANCED_CONTROL_COMMANDS = 9;
pub const ACTL_GETFARHWND: ADVANCED_CONTROL_COMMANDS = 10;
pub const ACTL_SETARRAYCOLOR: ADVANCED_CONTROL_COMMANDS = 16;
pub const ACTL_REDRAWALL: ADVANCED_CONTROL_COMMANDS = 19;
pub const ACTL_SYNCHRO: ADVANCED_CONTROL_COMMANDS = 20;
pub const ACTL_SETPROGRESSSTATE: ADVANCED_CONTROL_COMMANDS = 21;
pub const ACTL_SETPROGRESSVALUE: ADVANCED_CONTROL_COMMANDS = 22;
pub const ACTL_QUIT: ADVANCED_CONTROL_COMMANDS = 23;
pub const ACTL_GETFARRECT: ADVANCED_CONTROL_COMMANDS = 24;
pub const ACTL_GETCURSORPOS: ADVANCED_CONTROL_COMMANDS = 25;
pub const ACTL_SETCURSORPOS: ADVANCED_CONTROL_COMMANDS = 26;
pub const ACTL_PROGRESSNOTIFY: ADVANCED_CONTROL_COMMANDS = 27;
pub const ACTL_GETWINDOWTYPE: ADVANCED_CONTROL_COMMANDS = 28;

pub type TASKBARPROGRESSTYPE = i32;
pub const PS_NOPROGRESS: TASKBARPROGRESSTYPE = 0;
pub const PS_INDETERMINATE: TASKBARPROGRESSTYPE = 1;
pub const PS_NORMAL: TASKBARPROGRESSTYPE = 2;
pub const PS_ERROR: TASKBARPROGRESSTYPE = 4;
pub const PS_PAUSED: TASKBARPROGRESSTYPE = 8;

pub type FAR_MACRO_CONTROL_COMMANDS = i32;
pub const MCTL_LOADALL: FAR_MACRO_CONTROL_COMMANDS = 0;
pub const MCTL_SAVEALL: FAR_MACRO_CONTROL_COMMANDS = 1;
pub const MCTL_SENDSTRING: FAR_MACRO_CONTROL_COMMANDS = 2;
pub const MCTL_GETSTATE: FAR_MACRO_CONTROL_COMMANDS = 5;
pub const MCTL_GETAREA: FAR_MACRO_CONTROL_COMMANDS = 6;
pub const MCTL_ADDMACRO: FAR_MACRO_CONTROL_COMMANDS = 7;
pub const MCTL_DELMACRO: FAR_MACRO_CONTROL_COMMANDS = 8;
pub const MCTL_GETLASTERROR: FAR_MACRO_CONTROL_COMMANDS = 9;
pub const MCTL_EXECSTRING: FAR_MACRO_CONTROL_COMMANDS = 10;

pub type FARMACROSENDSTRINGCOMMAND = i32;
pub const MSSC_POST: FARMACROSENDSTRINGCOMMAND = 0;
pub const MSSC_CHECK: FARMACROSENDSTRINGCOMMAND = 2;

pub type FARMACROAREA = i32;
pub const MACROAREA_OTHER: FARMACROAREA = 0;
pub const MACROAREA_SHELL: FARMACROAREA = 1;
pub const MACROAREA_VIEWER: FARMACROAREA = 2;
pub const MACROAREA_EDITOR: FARMACROAREA = 3;
pub const MACROAREA_DIALOG: FARMACROAREA = 4;
pub const MACROAREA_SEARCH: FARMACROAREA = 5;
pub const MACROAREA_DISKS: FARMACROAREA = 6;
pub const MACROAREA_MAINMENU: FARMACROAREA = 7;
pub const MACROAREA_MENU: FARMACROAREA = 8;
pub const MACROAREA_HELP: FARMACROAREA = 9;
pub const MACROAREA_INFOPANEL: FARMACROAREA = 10;
pub const MACROAREA_QVIEWPANEL: FARMACROAREA = 11;
pub const MACROAREA_TREEPANEL: FARMACROAREA = 12;
pub const MACROAREA_FINDFOLDER: FARMACROAREA = 13;
pub const MACROAREA_USERMENU: FARMACROAREA = 14;
pub const MACROAREA_SHELLAUTOCOMPLETION: FARMACROAREA = 15;
pub const MACROAREA_DIALOGAUTOCOMPLETION: FARMACROAREA = 16;
pub const MACROAREA_GRABBER: FARMACROAREA = 17;
pub const MACROAREA_DESKTOP: FARMACROAREA = 18;
pub const MACROAREA_COMMON: FARMACROAREA = 255;

pub type FARMACROSTATE = i32;
pub const MACROSTATE_NOMACRO: FARMACROSTATE = 0;
pub const MACROSTATE_EXECUTING: FARMACROSTATE = 1;
pub const MACROSTATE_EXECUTING_COMMON: FARMACROSTATE = 2;
pub const MACROSTATE_RECORDING: FARMACROSTATE = 3;
pub const MACROSTATE_RECORDING_COMMON: FARMACROSTATE = 4;

pub type FARMACROPARSEERRORCODE = i32;
pub const MPEC_SUCCESS: FARMACROPARSEERRORCODE = 0;
pub const MPEC_ERROR: FARMACROPARSEERRORCODE = 1;

pub type EXPAND_TABS = i32;
pub const EXPAND_NOTABS: EXPAND_TABS = 0;
pub const EXPAND_ALLTABS: EXPAND_TABS = 1;
pub const EXPAND_NEWTABS: EXPAND_TABS = 2;

pub type EDITOR_BLOCK_TYPES = i32;
pub const BTYPE_NONE: EDITOR_BLOCK_TYPES = 0;
pub const BTYPE_STREAM: EDITOR_BLOCK_TYPES = 1;
pub const BTYPE_COLUMN: EDITOR_BLOCK_TYPES = 2;

pub type FAR_PLUGIN_LOAD_TYPE = i32;
pub const PLT_PATH: FAR_PLUGIN_LOAD_TYPE = 0;

pub type FAR_PLUGIN_FIND_TYPE = i32;
pub const PFM_GUID: FAR_PLUGIN_FIND_TYPE = 0;
pub const PFM_MODULENAME: FAR_PLUGIN_FIND_TYPE = 1;

pub type FAR_FILE_FILTER_TYPE = i32;
pub const FFT_PANEL: FAR_FILE_FILTER_TYPE = 0;
pub const FFT_FINDFILE: FAR_FILE_FILTER_TYPE = 1;
pub const FFT_COPY: FAR_FILE_FILTER_TYPE = 2;
pub const FFT_SELECT: FAR_FILE_FILTER_TYPE = 3;
pub const FFT_CUSTOM: FAR_FILE_FILTER_TYPE = 4;

pub type LINK_TYPE = i32;
pub const LINK_HARDLINK: LINK_TYPE = 1;
pub const LINK_JUNCTION: LINK_TYPE = 2;
pub const LINK_VOLMOUNT: LINK_TYPE = 3;
pub const LINK_SYMLINKFILE: LINK_TYPE = 4;
pub const LINK_SYMLINKDIR: LINK_TYPE = 5;
pub const LINK_SYMLINK: LINK_TYPE = 6;

pub type CONVERTPATHMODES = i32;
pub const CPM_FULL: CONVERTPATHMODES = 0;
pub const CPM_REAL: CONVERTPATHMODES = 1;
pub const CPM_NATIVE: CONVERTPATHMODES = 2;

// --- FAR Flags ---
pub type FARCOLORFLAGS = u64;
pub const FCF_FG_INDEX: FARCOLORFLAGS = 0x0000000000000001;
pub const FCF_BG_INDEX: FARCOLORFLAGS = 0x0000000000000002;
pub const FCF_FG_UNDERLINE_INDEX: FARCOLORFLAGS = 0x0000000000000008;
pub const FCF_INDEXMASK: FARCOLORFLAGS = 0x000000000000000B;
pub const FCF_INHERIT_STYLE: FARCOLORFLAGS = 0x0000000000000004;
pub const FCF_RAWATTR_MASK: FARCOLORFLAGS = 0x000000000000FF00;
pub const FCF_FG_BOLD: FARCOLORFLAGS = 0x1000000000000000;
pub const FCF_FG_ITALIC: FARCOLORFLAGS = 0x2000000000000000;
pub const FCF_FG_U_DATA0: FARCOLORFLAGS = 0x4000000000000000;
pub const FCF_FG_U_DATA1: FARCOLORFLAGS = 0x8000000000000000;
pub const FCF_FG_OVERLINE: FARCOLORFLAGS = 0x0100000000000000;
pub const FCF_FG_STRIKEOUT: FARCOLORFLAGS = 0x0200000000000000;
pub const FCF_FG_FAINT: FARCOLORFLAGS = 0x0400000000000000;
pub const FCF_FG_BLINK: FARCOLORFLAGS = 0x0800000000000000;
pub const FCF_INVERSE: FARCOLORFLAGS = 0x0010000000000000;
pub const FCF_FG_INVISIBLE: FARCOLORFLAGS = 0x0020000000000000;
pub const FCF_FG_U_DATA2: FARCOLORFLAGS = 0x0040000000000000;
pub const FCF_FG_UNDERLINE_MASK: FARCOLORFLAGS = 0xC040000000000000;
pub const FCF_STYLE_MASK: FARCOLORFLAGS = 0xFFF0000000000000;
pub const FCF_NONE: FARCOLORFLAGS = 0;

pub type FARMESSAGEFLAGS = u64;
pub const FMSG_WARNING: FARMESSAGEFLAGS = 0x0000000000000001;
pub const FMSG_ERRORTYPE: FARMESSAGEFLAGS = 0x0000000000000002;
pub const FMSG_KEEPBACKGROUND: FARMESSAGEFLAGS = 0x0000000000000004;
pub const FMSG_LEFTALIGN: FARMESSAGEFLAGS = 0x0000000000000008;
pub const FMSG_ALLINONE: FARMESSAGEFLAGS = 0x0000000000000010;
pub const FMSG_MB_OK: FARMESSAGEFLAGS = 0x0000000000010000;
pub const FMSG_MB_OKCANCEL: FARMESSAGEFLAGS = 0x0000000000020000;
pub const FMSG_MB_ABORTRETRYIGNORE: FARMESSAGEFLAGS = 0x0000000000030000;
pub const FMSG_MB_YESNO: FARMESSAGEFLAGS = 0x0000000000040000;
pub const FMSG_MB_YESNOCANCEL: FARMESSAGEFLAGS = 0x0000000000050000;
pub const FMSG_MB_RETRYCANCEL: FARMESSAGEFLAGS = 0x0000000000060000;
pub const FMSG_NONE: FARMESSAGEFLAGS = 0;

pub type FARDIALOGITEMFLAGS = u64;
pub const DIF_BOXCOLOR: FARDIALOGITEMFLAGS = 0x0000000000000200;
pub const DIF_GROUP: FARDIALOGITEMFLAGS = 0x0000000000000400;
pub const DIF_LEFTTEXT: FARDIALOGITEMFLAGS = 0x0000000000000800;
pub const DIF_MOVESELECT: FARDIALOGITEMFLAGS = 0x0000000000001000;
pub const DIF_SHOWAMPERSAND: FARDIALOGITEMFLAGS = 0x0000000000002000;
pub const DIF_CENTERGROUP: FARDIALOGITEMFLAGS = 0x0000000000004000;
pub const DIF_NOBRACKETS: FARDIALOGITEMFLAGS = 0x0000000000008000;
pub const DIF_MANUALADDHISTORY: FARDIALOGITEMFLAGS = 0x0000000000008000;
pub const DIF_SEPARATOR: FARDIALOGITEMFLAGS = 0x0000000000010000;
pub const DIF_SEPARATOR2: FARDIALOGITEMFLAGS = 0x0000000000020000;
pub const DIF_EDITOR: FARDIALOGITEMFLAGS = 0x0000000000020000;
pub const DIF_LISTNOAMPERSAND: FARDIALOGITEMFLAGS = 0x0000000000020000;
pub const DIF_LISTNOBOX: FARDIALOGITEMFLAGS = 0x0000000000040000;
pub const DIF_HISTORY: FARDIALOGITEMFLAGS = 0x0000000000040000;
pub const DIF_BTNNOCLOSE: FARDIALOGITEMFLAGS = 0x0000000000040000;
pub const DIF_CENTERTEXT: FARDIALOGITEMFLAGS = 0x0000000000040000;
pub const DIF_SEPARATORUSER: FARDIALOGITEMFLAGS = 0x0000000000080000;
pub const DIF_SETSHIELD: FARDIALOGITEMFLAGS = 0x0000000000080000;
pub const DIF_EDITEXPAND: FARDIALOGITEMFLAGS = 0x0000000000080000;
pub const DIF_DROPDOWNLIST: FARDIALOGITEMFLAGS = 0x0000000000100000;
pub const DIF_USELASTHISTORY: FARDIALOGITEMFLAGS = 0x0000000000200000;
pub const DIF_MASKEDIT: FARDIALOGITEMFLAGS = 0x0000000000400000;
pub const DIF_LISTTRACKMOUSE: FARDIALOGITEMFLAGS = 0x0000000000400000;
pub const DIF_LISTTRACKMOUSEINFOCUS: FARDIALOGITEMFLAGS = 0x0000000000800000;
pub const DIF_SELECTONENTRY: FARDIALOGITEMFLAGS = 0x0000000000800000;
pub const DIF_3STATE: FARDIALOGITEMFLAGS = 0x0000000000800000;
pub const DIF_EDITPATH: FARDIALOGITEMFLAGS = 0x0000000001000000;
pub const DIF_LISTWRAPMODE: FARDIALOGITEMFLAGS = 0x0000000001000000;
pub const DIF_NOAUTOCOMPLETE: FARDIALOGITEMFLAGS = 0x0000000002000000;
pub const DIF_LISTAUTOHIGHLIGHT: FARDIALOGITEMFLAGS = 0x0000000002000000;
pub const DIF_LISTNOCLOSE: FARDIALOGITEMFLAGS = 0x0000000004000000;
pub const DIF_EDITPATHEXEC: FARDIALOGITEMFLAGS = 0x0000000004000000;
pub const DIF_HIDDEN: FARDIALOGITEMFLAGS = 0x0000000010000000;
pub const DIF_READONLY: FARDIALOGITEMFLAGS = 0x0000000020000000;
pub const DIF_NOFOCUS: FARDIALOGITEMFLAGS = 0x0000000040000000;
pub const DIF_DISABLE: FARDIALOGITEMFLAGS = 0x0000000080000000;
pub const DIF_DEFAULTBUTTON: FARDIALOGITEMFLAGS = 0x0000000100000000;
pub const DIF_FOCUS: FARDIALOGITEMFLAGS = 0x0000000200000000;
pub const DIF_RIGHTTEXT: FARDIALOGITEMFLAGS = 0x0000000400000000;
pub const DIF_WORDWRAP: FARDIALOGITEMFLAGS = 0x0000000800000000;
pub const DIF_HOMEITEM: FARDIALOGITEMFLAGS = 0x0000002000000000;
pub const DIF_NONE: FARDIALOGITEMFLAGS = 0;

pub type LISTITEMFLAGS = u64;
pub const LIF_SELECTED: LISTITEMFLAGS = 0x0000000000010000;
pub const LIF_CHECKED: LISTITEMFLAGS = 0x0000000000020000;
pub const LIF_SEPARATOR: LISTITEMFLAGS = 0x0000000000040000;
pub const LIF_DISABLE: LISTITEMFLAGS = 0x0000000000080000;
pub const LIF_GRAYED: LISTITEMFLAGS = 0x0000000000100000;
pub const LIF_HIDDEN: LISTITEMFLAGS = 0x0000000000200000;
pub const LIF_DELETEUSERDATA: LISTITEMFLAGS = 0x0000000080000000;
pub const LIF_NONE: LISTITEMFLAGS = 0;

pub type FARLISTFINDFLAGS = u64;
pub const LIFIND_EXACTMATCH: FARLISTFINDFLAGS = 0x0000000000000001;
pub const LIFIND_NONE: FARLISTFINDFLAGS = 0;

pub type FARLISTINFOFLAGS = u64;
pub const LINFO_SHOWNOBOX: FARLISTINFOFLAGS = 0x0000000000000400;
pub const LINFO_AUTOHIGHLIGHT: FARLISTINFOFLAGS = 0x0000000000000800;
pub const LINFO_REVERSEHIGHLIGHT: FARLISTINFOFLAGS = 0x0000000000001000;
pub const LINFO_WRAPMODE: FARLISTINFOFLAGS = 0x0000000000008000;
pub const LINFO_SHOWAMPERSAND: FARLISTINFOFLAGS = 0x0000000000010000;
pub const LINFO_NONE: FARLISTINFOFLAGS = 0;

pub type FARDIALOGFLAGS = u64;
pub const FDLG_WARNING: FARDIALOGFLAGS = 0x0000000000000001;
pub const FDLG_SMALLDIALOG: FARDIALOGFLAGS = 0x0000000000000002;
pub const FDLG_NODRAWSHADOW: FARDIALOGFLAGS = 0x0000000000000004;
pub const FDLG_NODRAWPANEL: FARDIALOGFLAGS = 0x0000000000000008;
pub const FDLG_KEEPCONSOLETITLE: FARDIALOGFLAGS = 0x0000000000000010;
pub const FDLG_NONMODAL: FARDIALOGFLAGS = 0x0000000000000020;
pub const FDLG_STAY_ON_TOP: FARDIALOGFLAGS = 0x0000000000000040;
pub const FDLG_NONE: FARDIALOGFLAGS = 0;

pub type MENUITEMFLAGS = u64;
pub const MIF_SELECTED: MENUITEMFLAGS = 0x0000000000010000;
pub const MIF_CHECKED: MENUITEMFLAGS = 0x0000000000020000;
pub const MIF_SEPARATOR: MENUITEMFLAGS = 0x0000000000040000;
pub const MIF_DISABLE: MENUITEMFLAGS = 0x0000000000080000;
pub const MIF_GRAYED: MENUITEMFLAGS = 0x0000000000100000;
pub const MIF_HIDDEN: MENUITEMFLAGS = 0x0000000000200000;
pub const MIF_NONE: MENUITEMFLAGS = 0;

pub type FARMENUFLAGS = u64;
pub const FMENU_SHOWAMPERSAND: FARMENUFLAGS = 0x0000000000000001;
pub const FMENU_WRAPMODE: FARMENUFLAGS = 0x0000000000000002;
pub const FMENU_AUTOHIGHLIGHT: FARMENUFLAGS = 0x0000000000000004;
pub const FMENU_REVERSEAUTOHIGHLIGHT: FARMENUFLAGS = 0x0000000000000008;
pub const FMENU_CHANGECONSOLETITLE: FARMENUFLAGS = 0x0000000000000010;
pub const FMENU_SHOWNOBOX: FARMENUFLAGS = 0x0000000000000020;
pub const FMENU_SHOWSHORTBOX: FARMENUFLAGS = 0x0000000000000040;
pub const FMENU_SHOWSINGLEBOX: FARMENUFLAGS = 0x0000000000000080;
pub const FMENU_NODRAWSHADOW: FARMENUFLAGS = 0x0000000000000100;
pub const FMENU_NONE: FARMENUFLAGS = 0;

pub type PLUGINPANELITEMFLAGS = u64;
pub const PPIF_SELECTED: PLUGINPANELITEMFLAGS = 0x0000000040000000;
pub const PPIF_PROCESSDESCR: PLUGINPANELITEMFLAGS = 0x0000000080000000;
pub const PPIF_NONE: PLUGINPANELITEMFLAGS = 0;

pub type PANELINFOFLAGS = u64;
pub const PFLAGS_SHOWHIDDEN: PANELINFOFLAGS = 0x0000000000000001;
pub const PFLAGS_HIGHLIGHT: PANELINFOFLAGS = 0x0000000000000002;
pub const PFLAGS_REVERSESORTORDER: PANELINFOFLAGS = 0x0000000000000004;
pub const PFLAGS_USESORTGROUPS: PANELINFOFLAGS = 0x0000000000000008;
pub const PFLAGS_SELECTEDFIRST: PANELINFOFLAGS = 0x0000000000000010;
pub const PFLAGS_REALNAMES: PANELINFOFLAGS = 0x0000000000000020;
pub const PFLAGS_PANELLEFT: PANELINFOFLAGS = 0x0000000000000080;
pub const PFLAGS_DIRECTORIESFIRST: PANELINFOFLAGS = 0x0000000000000100;
pub const PFLAGS_USECRC32: PANELINFOFLAGS = 0x0000000000000200;
pub const PFLAGS_PLUGIN: PANELINFOFLAGS = 0x0000000000000800;
pub const PFLAGS_VISIBLE: PANELINFOFLAGS = 0x0000000000001000;
pub const PFLAGS_FOCUS: PANELINFOFLAGS = 0x0000000000002000;
pub const PFLAGS_ALTERNATIVENAMES: PANELINFOFLAGS = 0x0000000000004000;
pub const PFLAGS_SHORTCUT: PANELINFOFLAGS = 0x0000000000008000;
pub const PFLAGS_NONE: PANELINFOFLAGS = 0;

pub type VIEWER_FLAGS = u64;
pub const VF_NONMODAL: VIEWER_FLAGS = 0x0000000000000001;
pub const VF_DELETEONCLOSE: VIEWER_FLAGS = 0x0000000000000002;
pub const VF_ENABLE_F6: VIEWER_FLAGS = 0x0000000000000004;
pub const VF_DISABLEHISTORY: VIEWER_FLAGS = 0x0000000000000008;
pub const VF_IMMEDIATERETURN: VIEWER_FLAGS = 0x0000000000000100;
pub const VF_DELETEONLYFILEONCLOSE: VIEWER_FLAGS = 0x0000000000000200;
pub const VF_NONE: VIEWER_FLAGS = 0;

pub type EDITOR_FLAGS = u64;
pub const EF_NONMODAL: EDITOR_FLAGS = 0x0000000000000001;
pub const EF_CREATENEW: EDITOR_FLAGS = 0x0000000000000002;
pub const EF_ENABLE_F6: EDITOR_FLAGS = 0x0000000000000004;
pub const EF_DISABLEHISTORY: EDITOR_FLAGS = 0x0000000000000008;
pub const EF_DELETEONCLOSE: EDITOR_FLAGS = 0x0000000000000010;
pub const EF_IMMEDIATERETURN: EDITOR_FLAGS = 0x0000000000000100;
pub const EF_DELETEONLYFILEONCLOSE: EDITOR_FLAGS = 0x0000000000000200;
pub const EF_LOCKED: EDITOR_FLAGS = 0x0000000000000400;
pub const EF_DISABLESAVEPOS: EDITOR_FLAGS = 0x0000000000000800;
pub const EF_OPENMODE_MASK: EDITOR_FLAGS = 0x00000000F0000000;
pub const EF_OPENMODE_QUERY: EDITOR_FLAGS = 0x0000000000000000;
pub const EF_OPENMODE_NEWIFOPEN: EDITOR_FLAGS = 0x0000000010000000;
pub const EF_OPENMODE_USEEXISTING: EDITOR_FLAGS = 0x0000000020000000;
pub const EF_OPENMODE_BREAKIFOPEN: EDITOR_FLAGS = 0x0000000030000000;
pub const EF_OPENMODE_RELOADIFOPEN: EDITOR_FLAGS = 0x0000000040000000;
pub const EF_NONE: EDITOR_FLAGS = 0;

pub type FARHELPFLAGS = u64;
pub const FHELP_NOSHOWERROR: FARHELPFLAGS = 0x0000000080000000;
pub const FHELP_SELFHELP: FARHELPFLAGS = 0x0000000000000000;
pub const FHELP_FARHELP: FARHELPFLAGS = 0x0000000000000001;
pub const FHELP_CUSTOMFILE: FARHELPFLAGS = 0x0000000000000002;
pub const FHELP_CUSTOMPATH: FARHELPFLAGS = 0x0000000000000004;
pub const FHELP_GUID: FARHELPFLAGS = 0x0000000000000008;
pub const FHELP_USECONTENTS: FARHELPFLAGS = 0x0000000040000000;
pub const FHELP_NONE: FARHELPFLAGS = 0;

pub type FARKEYMACROFLAGS = u64;
pub const KMFLAGS_SILENTCHECK: FARKEYMACROFLAGS = 0x0000000000000001;
pub const KMFLAGS_NOSENDKEYSTOPLUGINS: FARKEYMACROFLAGS = 0x0000000000000002;
pub const KMFLAGS_ENABLEOUTPUT: FARKEYMACROFLAGS = 0x0000000000000004;
pub const KMFLAGS_LANGMASK: FARKEYMACROFLAGS = 0x0000000000000070;
pub const KMFLAGS_LUA: FARKEYMACROFLAGS = 0x0000000000000000;
pub const KMFLAGS_MOONSCRIPT: FARKEYMACROFLAGS = 0x0000000000000010;
pub const KMFLAGS_NONE: FARKEYMACROFLAGS = 0;

pub type FARADDKEYMACROFLAGS = u64;
pub const AKMFLAGS_NONE: FARADDKEYMACROFLAGS = 0;

pub type FARSETCOLORFLAGS = u64;
pub const FSETCLR_REDRAW: FARSETCOLORFLAGS = 0x0000000000000001;
pub const FSETCLR_NONE: FARSETCOLORFLAGS = 0;

pub type WINDOWINFO_FLAGS = u64;
pub const WIF_MODIFIED: WINDOWINFO_FLAGS = 0x0000000000000001;
pub const WIF_CURRENT: WINDOWINFO_FLAGS = 0x0000000000000002;
pub const WIF_MODAL: WINDOWINFO_FLAGS = 0x0000000000000004;
pub const WIF_NONE: WINDOWINFO_FLAGS = 0;

pub type VIEWER_OPTIONS = u64;
pub const VOPT_SAVEFILEPOSITION: VIEWER_OPTIONS = 0x0000000000000001;
pub const VOPT_AUTODETECTCODEPAGE: VIEWER_OPTIONS = 0x0000000000000002;
pub const VOPT_SHOWTITLEBAR: VIEWER_OPTIONS = 0x0000000000000004;
pub const VOPT_SHOWKEYBAR: VIEWER_OPTIONS = 0x0000000000000008;
pub const VOPT_SHOWSCROLLBAR: VIEWER_OPTIONS = 0x0000000000000010;
pub const VOPT_QUICKVIEW: VIEWER_OPTIONS = 0x0000000000000020;
pub const VOPT_NONE: VIEWER_OPTIONS = 0;

pub type VIEWER_SETMODEFLAGS_TYPES = u64;
pub const VSMFL_REDRAW: VIEWER_SETMODEFLAGS_TYPES = 0x0000000000000001;
pub const VSMFL_NONE: VIEWER_SETMODEFLAGS_TYPES = 0;

pub type VIEWER_SETPOS_FLAGS = u64;
pub const VSP_NOREDRAW: VIEWER_SETPOS_FLAGS = 0x0000000000000001;
pub const VSP_PERCENT: VIEWER_SETPOS_FLAGS = 0x0000000000000002;
pub const VSP_RELATIVE: VIEWER_SETPOS_FLAGS = 0x0000000000000004;
pub const VSP_NORETNEWPOS: VIEWER_SETPOS_FLAGS = 0x0000000000000008;
pub const VSP_NONE: VIEWER_SETPOS_FLAGS = 0;

pub type VIEWER_MODE_FLAGS = u64;
pub const VMF_WRAP: VIEWER_MODE_FLAGS = 0x0000000000000001;
pub const VMF_WORDWRAP: VIEWER_MODE_FLAGS = 0x0000000000000002;
pub const VMF_NONE: VIEWER_MODE_FLAGS = 0;

pub type EDITORCOLORFLAGS = u64;
pub const ECF_TABMARKFIRST: EDITORCOLORFLAGS = 0x0000000000000001;
pub const ECF_TABMARKCURRENT: EDITORCOLORFLAGS = 0x0000000000000002;
pub const ECF_AUTODELETE: EDITORCOLORFLAGS = 0x0000000000000004;
pub const ECF_NONE: EDITORCOLORFLAGS = 0;

pub type INPUTBOXFLAGS = u64;
pub const FIB_ENABLEEMPTY: INPUTBOXFLAGS = 0x0000000000000001;
pub const FIB_PASSWORD: INPUTBOXFLAGS = 0x0000000000000002;
pub const FIB_EXPANDENV: INPUTBOXFLAGS = 0x0000000000000004;
pub const FIB_NOUSELASTHISTORY: INPUTBOXFLAGS = 0x0000000000000008;
pub const FIB_BUTTONS: INPUTBOXFLAGS = 0x0000000000000010;
pub const FIB_NOAMPERSAND: INPUTBOXFLAGS = 0x0000000000000020;
pub const FIB_EDITPATH: INPUTBOXFLAGS = 0x0000000000000040;
pub const FIB_EDITPATHEXEC: INPUTBOXFLAGS = 0x0000000000000080;
pub const FIB_NONE: INPUTBOXFLAGS = 0;

pub type FAR_PLUGIN_FLAGS = u64;
pub const FPF_LOADED: FAR_PLUGIN_FLAGS = 0x0000000000000001;
pub const FPF_ANSI: FAR_PLUGIN_FLAGS = 0x1000000000000000;
pub const FPF_NONE: FAR_PLUGIN_FLAGS = 0;

pub type PROCESSNAME_FLAGS = u64;
pub const PN_CMPNAME: PROCESSNAME_FLAGS = 0x0000000000000000;
pub const PN_CMPNAMELIST: PROCESSNAME_FLAGS = 0x0000000000010000;
pub const PN_GENERATENAME: PROCESSNAME_FLAGS = 0x0000000000020000;
pub const PN_CHECKMASK: PROCESSNAME_FLAGS = 0x0000000000030000;
pub const PN_SKIPPATH: PROCESSNAME_FLAGS = 0x0000000001000000;
pub const PN_SHOWERRORMESSAGE: PROCESSNAME_FLAGS = 0x0000000002000000;
pub const PN_NONE: PROCESSNAME_FLAGS = 0;

pub type XLAT_FLAGS = u64;
pub const XLAT_SWITCHKEYBLAYOUT: XLAT_FLAGS = 0x0000000000000001;
pub const XLAT_SWITCHKEYBBEEP: XLAT_FLAGS = 0x0000000000000002;
pub const XLAT_USEKEYBLAYOUTNAME: XLAT_FLAGS = 0x0000000000000004;
pub const XLAT_CONVERTALLCMDLINE: XLAT_FLAGS = 0x0000000000010000;
pub const XLAT_NONE: XLAT_FLAGS = 0;

pub type FRSMODE = u64;
pub const FRS_RETUPDIR: FRSMODE = 0x0000000000000001;
pub const FRS_RECUR: FRSMODE = 0x0000000000000002;
pub const FRS_SCANSYMLINK: FRSMODE = 0x0000000000000004;
pub const FRS_NONE: FRSMODE = 0;

pub type MKLINK_FLAGS = u64;
pub const MLF_SHOWERRMSG: MKLINK_FLAGS = 0x0000000000010000;
pub const MLF_DONOTUPDATEPANEL: MKLINK_FLAGS = 0x0000000000020000;
pub const MLF_HOLDTARGET: MKLINK_FLAGS = 0x0000000000040000;
pub const MLF_NONE: MKLINK_FLAGS = 0;

pub type FARFORMATFILESIZEFLAGS = u64;
pub const FFFS_COMMAS: FARFORMATFILESIZEFLAGS = 0x0100000000000000;
pub const FFFS_FLOATSIZE: FARFORMATFILESIZEFLAGS = 0x0200000000000000;
pub const FFFS_SHOWBYTESINDEX: FARFORMATFILESIZEFLAGS = 0x0400000000000000;
pub const FFFS_ECONOMIC: FARFORMATFILESIZEFLAGS = 0x0800000000000000;
pub const FFFS_THOUSAND: FARFORMATFILESIZEFLAGS = 0x1000000000000000;
pub const FFFS_MINSIZEINDEX: FARFORMATFILESIZEFLAGS = 0x2000000000000000;
pub const FFFS_MINSIZEINDEX_MASK: FARFORMATFILESIZEFLAGS = 0x0000000000000007;
pub const FFFS_NONE: FARFORMATFILESIZEFLAGS = 0;

pub type PLUGIN_FLAGS = u64;
pub const PF_PRELOAD: PLUGIN_FLAGS = 0x0000000000000001;
pub const PF_DISABLEPANELS: PLUGIN_FLAGS = 0x0000000000000002;
pub const PF_EDITOR: PLUGIN_FLAGS = 0x0000000000000004;
pub const PF_VIEWER: PLUGIN_FLAGS = 0x0000000000000008;
pub const PF_FULLCMDLINE: PLUGIN_FLAGS = 0x0000000000000010;
pub const PF_DIALOG: PLUGIN_FLAGS = 0x0000000000000020;
pub const PF_NONE: PLUGIN_FLAGS = 0;

pub type INFOPANELLINE_FLAGS = u64;
pub const IPLFLAGS_SEPARATOR: INFOPANELLINE_FLAGS = 0x0000000000000001;
pub const IPLFLAGS_NONE: INFOPANELLINE_FLAGS = 0;

pub type PANELMODE_FLAGS = u64;
pub const PMFLAGS_FULLSCREEN: PANELMODE_FLAGS = 0x0000000000000001;
pub const PMFLAGS_DETAILEDSTATUS: PANELMODE_FLAGS = 0x0000000000000002;
pub const PMFLAGS_ALIGNEXTENSIONS: PANELMODE_FLAGS = 0x0000000000000004;
pub const PMFLAGS_CASECONVERSION: PANELMODE_FLAGS = 0x0000000000000008;
pub const PMFLAGS_NONE: PANELMODE_FLAGS = 0;

pub type OPENPANELINFO_FLAGS = u64;
pub const OPIF_DISABLEFILTER: OPENPANELINFO_FLAGS = 0x0000000000000001;
pub const OPIF_DISABLESORTGROUPS: OPENPANELINFO_FLAGS = 0x0000000000000002;
pub const OPIF_DISABLEHIGHLIGHTING: OPENPANELINFO_FLAGS = 0x0000000000000004;
pub const OPIF_ADDDOTS: OPENPANELINFO_FLAGS = 0x0000000000000008;
pub const OPIF_RAWSELECTION: OPENPANELINFO_FLAGS = 0x0000000000000010;
pub const OPIF_REALNAMES: OPENPANELINFO_FLAGS = 0x0000000000000020;
pub const OPIF_SHOWNAMESONLY: OPENPANELINFO_FLAGS = 0x0000000000000040;
pub const OPIF_SHOWRIGHTALIGNNAMES: OPENPANELINFO_FLAGS = 0x0000000000000080;
pub const OPIF_SHOWPRESERVECASE: OPENPANELINFO_FLAGS = 0x0000000000000100;
pub const OPIF_COMPAREFATTIME: OPENPANELINFO_FLAGS = 0x0000000000000400;
pub const OPIF_EXTERNALGET: OPENPANELINFO_FLAGS = 0x0000000000000800;
pub const OPIF_EXTERNALPUT: OPENPANELINFO_FLAGS = 0x0000000000001000;
pub const OPIF_EXTERNALDELETE: OPENPANELINFO_FLAGS = 0x0000000000002000;
pub const OPIF_EXTERNALMKDIR: OPENPANELINFO_FLAGS = 0x0000000000004000;
pub const OPIF_USEATTRHIGHLIGHTING: OPENPANELINFO_FLAGS = 0x0000000000008000;
pub const OPIF_USECRC32: OPENPANELINFO_FLAGS = 0x0000000000010000;
pub const OPIF_USEFREESIZE: OPENPANELINFO_FLAGS = 0x0000000000020000;
pub const OPIF_SHORTCUT: OPENPANELINFO_FLAGS = 0x0000000000040000;
pub const OPIF_RECURSIVEPANEL: OPENPANELINFO_FLAGS = 0x0000000000080000;
pub const OPIF_DELETEFILEONCLOSE: OPENPANELINFO_FLAGS = 0x0000000000100000;
pub const OPIF_DELETEDIRONCLOSE: OPENPANELINFO_FLAGS = 0x0000000000200000;
pub const OPIF_NONE: OPENPANELINFO_FLAGS = 0;

pub type OPERATION_MODES = u64;
pub const OPM_SILENT: OPERATION_MODES = 0x0000000000000001;
pub const OPM_FIND: OPERATION_MODES = 0x0000000000000002;
pub const OPM_VIEW: OPERATION_MODES = 0x0000000000000004;
pub const OPM_EDIT: OPERATION_MODES = 0x0000000000000008;
pub const OPM_TOPLEVEL: OPERATION_MODES = 0x0000000000000010;
pub const OPM_DESCR: OPERATION_MODES = 0x0000000000000020;
pub const OPM_QUICKVIEW: OPERATION_MODES = 0x0000000000000040;
pub const OPM_PGDN: OPERATION_MODES = 0x0000000000000080;
pub const OPM_COMMANDS: OPERATION_MODES = 0x0000000000000100;
pub const OPM_NONE: OPERATION_MODES = 0;

pub type FAROPENSHORTCUTFLAGS = u64;
pub const FOSF_ACTIVE: FAROPENSHORTCUTFLAGS = 0x0000000000000001;
pub const FOSF_NONE: FAROPENSHORTCUTFLAGS = 0;

pub type PROCESSCONSOLEINPUT_FLAGS = u64;
pub const PCIF_NONE: PROCESSCONSOLEINPUT_FLAGS = 0;

// --- FAR Structures ---
#[repr(C)]
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct rgba {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
}

#[repr(C)]
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct color_index {
    pub i: u8,
    pub reserved0: u8,
    pub reserved1: u8,
    pub a: u8,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union FarColorValue {
    pub ForegroundColor: COLORREF,
    pub ForegroundIndex: color_index,
    pub ForegroundRGBA: rgba,
}

impl Default for FarColorValue {
    fn default() -> Self {
        Self { ForegroundColor: 0 }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarColor {
    pub Flags: FARCOLORFLAGS,
    pub Foreground: FarColorValue,
    pub Background: FarColorValue,
    pub Underline: FarColorValue,
    pub Reserved: DWORD,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct VersionInfo {
    pub Major: DWORD,
    pub Minor: DWORD,
    pub Revision: DWORD,
    pub Build: DWORD,
    pub Stage: i32, // VERSION_STAGE
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PluginMenuItem {
    pub Guids: *const GUID,
    pub Strings: *const *const WCHAR,
    pub Count: usize,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct GlobalInfo {
    pub StructSize: usize,
    pub MinFarVersion: VersionInfo,
    pub Version: VersionInfo,
    pub Guid: GUID,
    pub Title: *const WCHAR,
    pub Description: *const WCHAR,
    pub Author: *const WCHAR,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PluginInfo {
    pub StructSize: usize,
    pub Flags: PLUGIN_FLAGS,
    pub DiskMenu: PluginMenuItem,
    pub PluginMenu: PluginMenuItem,
    pub PluginConfig: PluginMenuItem,
    pub CommandPrefix: *const WCHAR,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarPanelItemFreeInfo {
    pub StructSize: usize,
    pub hPlugin: HANDLE,
}

pub type FARPANELITEMFREECALLBACK = Option<unsafe extern "system" fn(UserData: *mut c_void, Info: *const FarPanelItemFreeInfo)>;

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct UserDataItem {
    pub Data: *mut c_void,
    pub FreeData: FARPANELITEMFREECALLBACK,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PluginPanelItem {
    pub CreationTime: FILETIME,
    pub LastAccessTime: FILETIME,
    pub LastWriteTime: FILETIME,
    pub ChangeTime: FILETIME,
    pub FileSize: u64,
    pub AllocationSize: u64,
    pub FileName: *const WCHAR,
    pub AlternateFileName: *const WCHAR,
    pub Description: *const WCHAR,
    pub Owner: *const WCHAR,
    pub CustomColumnData: *const *const WCHAR,
    pub CustomColumnNumber: usize,
    pub Flags: PLUGINPANELITEMFLAGS,
    pub UserData: UserDataItem,
    pub FileAttributes: UIntPtr,
    pub NumberOfLinks: UIntPtr,
    pub CRC32: UIntPtr,
    pub Reserved: [IntPtr; 2],
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct SortingPanelItem {
    pub CreationTime: FILETIME,
    pub LastAccessTime: FILETIME,
    pub LastWriteTime: FILETIME,
    pub ChangeTime: FILETIME,
    pub FileSize: u64,
    pub AllocationSize: u64,
    pub FileName: *const WCHAR,
    pub AlternateFileName: *const WCHAR,
    pub Description: *const WCHAR,
    pub Owner: *const WCHAR,
    pub CustomColumnData: *const *const WCHAR,
    pub CustomColumnNumber: usize,
    pub Flags: PLUGINPANELITEMFLAGS,
    pub UserData: UserDataItem,
    pub FileAttributes: UIntPtr,
    pub NumberOfLinks: UIntPtr,
    pub CRC32: UIntPtr,
    pub Position: IntPtr,
    pub SortGroup: IntPtr,
    pub NumberOfStreams: UIntPtr,
    pub StreamsSize: u64,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PanelInfo {
    pub StructSize: usize,
    pub PluginHandle: HANDLE,
    pub OwnerGuid: GUID,
    pub Flags: PANELINFOFLAGS,
    pub ItemsNumber: usize,
    pub SelectedItemsNumber: usize,
    pub PanelRect: RECT,
    pub CurrentItem: usize,
    pub TopPanelItem: usize,
    pub ViewMode: IntPtr,
    pub PanelType: PANELINFOTYPE,
    pub SortMode: OPENPANELINFO_SORTMODES,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct InfoPanelLine {
    pub Text: *const WCHAR,
    pub Data: *const WCHAR,
    pub Flags: INFOPANELLINE_FLAGS,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PanelMode {
    pub ColumnTypes: *const WCHAR,
    pub ColumnWidths: *const WCHAR,
    pub ColumnTitles: *const *const WCHAR,
    pub StatusColumnTypes: *const WCHAR,
    pub StatusColumnWidths: *const WCHAR,
    pub Flags: PANELMODE_FLAGS,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct KeyBarLabel {
    pub Key: FarKey,
    pub Text: *const WCHAR,
    pub LongText: *const WCHAR,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct KeyBarTitles {
    pub CountLabels: usize,
    pub Labels: *mut KeyBarLabel,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OpenPanelInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub Flags: OPENPANELINFO_FLAGS,
    pub HostFile: *const WCHAR,
    pub CurDir: *const WCHAR,
    pub Format: *const WCHAR,
    pub PanelTitle: *const WCHAR,
    pub InfoLines: *const InfoPanelLine,
    pub InfoLinesNumber: usize,
    pub DescrFiles: *const *const WCHAR,
    pub DescrFilesNumber: usize,
    pub PanelModesArray: *const PanelMode,
    pub PanelModesNumber: usize,
    pub StartPanelMode: IntPtr,
    pub StartSortMode: OPENPANELINFO_SORTMODES,
    pub StartSortOrder: IntPtr,
    pub KeyBar: *const KeyBarTitles,
    pub ShortcutData: *const WCHAR,
    pub FreeSize: u64,
    pub UserData: UserDataItem,
    pub Instance: *mut c_void,
}

pub type GetOpenPanelInfo = OpenPanelInfo;

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarKey {
    pub VirtualKeyCode: WORD,
    pub ControlKeyState: DWORD,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct AnalyseInfo {
    pub StructSize: usize,
    pub FileName: *const WCHAR,
    pub Buffer: *mut c_void,
    pub BufferSize: usize,
    pub OpMode: OPERATION_MODES,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OpenAnalyseInfo {
    pub StructSize: usize,
    pub Info: *mut AnalyseInfo,
    pub Handle: HANDLE,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OpenInfo {
    pub StructSize: usize,
    pub OpenFrom: OPENFROM,
    pub Guid: *const GUID,
    pub Data: IntPtr,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct SetDirectoryInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub Dir: *const WCHAR,
    pub Reserved: IntPtr,
    pub OpMode: OPERATION_MODES,
    pub UserData: UserDataItem,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct GetFindDataInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub PanelItem: *mut PluginPanelItem,
    pub ItemsNumber: usize,
    pub OpMode: OPERATION_MODES,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FreeFindDataInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub PanelItem: *mut PluginPanelItem,
    pub ItemsNumber: usize,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ClosePanelInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct CloseAnalyseInfo {
    pub StructSize: usize,
    pub Handle: HANDLE,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ExitInfo {
    pub StructSize: usize,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct SetFindListInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub PanelItem: *const PluginPanelItem,
    pub ItemsNumber: usize,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PutFilesInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub PanelItem: *mut PluginPanelItem,
    pub ItemsNumber: usize,
    pub Move: BOOL,
    pub SrcPath: *const WCHAR,
    pub OpMode: OPERATION_MODES,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessHostFileInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub PanelItem: *mut PluginPanelItem,
    pub ItemsNumber: usize,
    pub OpMode: OPERATION_MODES,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MakeDirectoryInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub Name: *const WCHAR,
    pub OpMode: OPERATION_MODES,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct CompareInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub Item1: *const PluginPanelItem,
    pub Item2: *const PluginPanelItem,
    pub Mode: OPENPANELINFO_SORTMODES,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct GetFilesInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub PanelItem: *mut PluginPanelItem,
    pub ItemsNumber: usize,
    pub Move: BOOL,
    pub DestPath: *const WCHAR,
    pub OpMode: OPERATION_MODES,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct DeleteFilesInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub PanelItem: *mut PluginPanelItem,
    pub ItemsNumber: usize,
    pub OpMode: OPERATION_MODES,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessPanelInputInfo {
    pub StructSize: usize,
    pub hPanel: HANDLE,
    pub Rec: INPUT_RECORD,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessEditorInputInfo {
    pub StructSize: usize,
    pub Rec: INPUT_RECORD,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessConsoleInputInfo {
    pub StructSize: usize,
    pub Flags: PROCESSCONSOLEINPUT_FLAGS,
    pub Rec: INPUT_RECORD,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OpenShortcutInfo {
    pub StructSize: usize,
    pub HostFile: *const WCHAR,
    pub ShortcutData: *const WCHAR,
    pub Flags: FAROPENSHORTCUTFLAGS,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OpenCommandLineInfo {
    pub StructSize: usize,
    pub CommandLine: *const WCHAR,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OpenMacroPluginInfo {
    pub CallType: MACROCALLTYPE,
    pub Data: *mut FarMacroCall,
    pub Ret: MacroPluginReturn,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OpenMacroInfo {
    pub StructSize: usize,
    pub Count: usize,
    pub Values: *mut FarMacroValue,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ArclitePrivateInfo {
    pub StructSize: usize,
    pub CreateFile: FARAPICREATEFILE,
    pub GetFileAttributes: FARAPIGETFILEATTRIBUTES,
    pub SetFileAttributes: FARAPISETFILEATTRIBUTES,
    pub MoveFileEx: FARAPIMOVEFILEEX,
    pub DeleteFile: FARAPIDELETEFILE,
    pub RemoveDirectory: FARAPIREMOVEDIRECTORY,
    pub CreateDirectory: FARAPICREATEDIRECTORY,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NetBoxPrivateInfo {
    pub StructSize: usize,
    pub CreateFile: FARAPICREATEFILE,
    pub GetFileAttributes: FARAPIGETFILEATTRIBUTES,
    pub SetFileAttributes: FARAPISETFILEATTRIBUTES,
    pub MoveFileEx: FARAPIMOVEFILEEX,
    pub DeleteFile: FARAPIDELETEFILE,
    pub RemoveDirectory: FARAPIREMOVEDIRECTORY,
    pub CreateDirectory: FARAPICREATEDIRECTORY,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MacroPrivateInfo {
    pub StructSize: usize,
    pub CallFar: FARAPICALLFAR,
}

// --- Event Structures ---
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessPanelEventInfo {
    pub StructSize: usize,
    pub Event: IntPtr,
    pub Param: *mut c_void,
    pub hPanel: HANDLE,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessEditorEventInfo {
    pub StructSize: usize,
    pub Event: IntPtr,
    pub Param: *mut c_void,
    pub EditorID: IntPtr,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarDialogEvent {
    pub StructSize: usize,
    pub hDlg: HANDLE,
    pub Msg: IntPtr,
    pub Param1: IntPtr,
    pub Param2: *mut c_void,
    pub Result: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessDialogEventInfo {
    pub StructSize: usize,
    pub Event: IntPtr,
    pub Param: *mut FarDialogEvent,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessSynchroEventInfo {
    pub StructSize: usize,
    pub Event: IntPtr,
    pub Param: *mut c_void,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ProcessViewerEventInfo {
    pub StructSize: usize,
    pub Event: IntPtr,
    pub Param: *mut c_void,
    pub ViewerID: IntPtr,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ConfigureInfo {
    pub StructSize: usize,
    pub Guid: *const GUID,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct GetContentFieldsInfo {
    pub StructSize: usize,
    pub Count: usize,
    pub Names: *const *const WCHAR,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct GetContentDataInfo {
    pub StructSize: usize,
    pub FilePath: *const WCHAR,
    pub Count: usize,
    pub Names: *const *const WCHAR,
    pub Values: *mut *const WCHAR,
    pub Instance: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ErrorInfo {
    pub StructSize: usize,
    pub Summary: *const WCHAR,
    pub Description: *const WCHAR,
}

// --- Macro API Structures ---
pub type FARMACROVARTYPE = i32;
pub const FMVT_UNKNOWN: FARMACROVARTYPE = 0;
pub const FMVT_INTEGER: FARMACROVARTYPE = 1;
pub const FMVT_STRING: FARMACROVARTYPE = 2;
pub const FMVT_DOUBLE: FARMACROVARTYPE = 3;
pub const FMVT_BOOLEAN: FARMACROVARTYPE = 4;
pub const FMVT_BINARY: FARMACROVARTYPE = 5;
pub const FMVT_POINTER: FARMACROVARTYPE = 6;
pub const FMVT_NIL: FARMACROVARTYPE = 7;
pub const FMVT_ARRAY: FARMACROVARTYPE = 8;
pub const FMVT_PANEL: FARMACROVARTYPE = 9;
pub const FMVT_ERROR: FARMACROVARTYPE = 10;
pub const FMVT_MBSTRING: FARMACROVARTYPE = 11;
pub const FMVT_NEWTABLE: FARMACROVARTYPE = 12;
pub const FMVT_SETTABLE: FARMACROVARTYPE = 13;
pub const FMVT_DIALOG: FARMACROVARTYPE = 14;
pub const FMVT_TABLE: FARMACROVARTYPE = 15;
pub const FMVT_GETTABLE: FARMACROVARTYPE = 16;
pub const FMVT_STACKPOP: FARMACROVARTYPE = 17;
pub const FMVT_STACKGETTOP: FARMACROVARTYPE = 18;
pub const FMVT_STACKSETTOP: FARMACROVARTYPE = 19;
pub const FMVT_STACKPUSHVALUE: FARMACROVARTYPE = 20;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct FarMacroValue {
    pub Type: FARMACROVARTYPE,
    pub Value: FarMacroValueData,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union FarMacroValueData {
    pub Integer: i64,
    pub Boolean: i64,
    pub Double: f64,
    pub String: *const WCHAR,
    pub MBString: *const i8,
    pub Pointer: *mut c_void,
    pub Binary: FarMacroBinary,
    pub Array: FarMacroArray,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct FarMacroBinary {
    pub Data: *mut c_void,
    pub Size: usize,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct FarMacroArray {
    pub Values: *mut FarMacroValue,
    pub Count: usize,
}

impl Default for FarMacroValueData {
    fn default() -> Self {
        Self { Integer: 0 }
    }
}

impl Default for FarMacroValue {
    fn default() -> Self {
        Self { Type: FMVT_NIL, Value: FarMacroValueData::default() }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarMacroCall {
    pub StructSize: usize,
    pub Count: usize,
    pub Values: *mut FarMacroValue,
    pub Callback: Option<unsafe extern "system" fn(CallbackData: *mut c_void, Values: *mut FarMacroValue, Count: usize)>,
    pub CallbackData: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MacroPluginReturn {
    pub ReturnType: IntPtr,
    pub Count: usize,
    pub Values: *mut FarMacroValue,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MacroParseResult {
    pub StructSize: usize,
    pub ErrCode: DWORD,
    pub ErrPos: COORD,
    pub ErrSrc: *const WCHAR,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MacroSendMacroText {
    pub StructSize: usize,
    pub Flags: FARKEYMACROFLAGS,
    pub AKey: INPUT_RECORD,
    pub SequenceText: *const WCHAR,
}

pub type FARMACROCALLBACK = Option<unsafe extern "system" fn(Id: *mut c_void, Flags: FARADDKEYMACROFLAGS) -> IntPtr>;

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MacroAddMacro {
    pub StructSize: usize,
    pub Id: *mut c_void,
    pub SequenceText: *const WCHAR,
    pub Description: *const WCHAR,
    pub Flags: FARKEYMACROFLAGS,
    pub AKey: INPUT_RECORD,
    pub Area: FARMACROAREA,
    pub Callback: FARMACROCALLBACK,
    pub Priority: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarGetValue {
    pub StructSize: usize,
    pub Type: IntPtr,
    pub Value: FarMacroValue,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MacroExecuteString {
    pub StructSize: usize,
    pub Flags: FARKEYMACROFLAGS,
    pub SequenceText: *const WCHAR,
    pub InCount: usize,
    pub InValues: *mut FarMacroValue,
    pub OutCount: usize,
    pub OutValues: *const FarMacroValue,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarMacroLoad {
    pub StructSize: usize,
    pub Path: *const WCHAR,
    pub Flags: u64,
}

// --- Window Info ---
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct WindowInfo {
    pub StructSize: usize,
    pub Id: IntPtr,
    pub TypeName: *mut WCHAR,
    pub Name: *mut WCHAR,
    pub TypeNameSize: IntPtr,
    pub NameSize: IntPtr,
    pub Pos: IntPtr,
    pub Type: WINDOWINFO_TYPE,
    pub Flags: WINDOWINFO_FLAGS,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct WindowType {
    pub StructSize: usize,
    pub Type: WINDOWINFO_TYPE,
}

// --- Settings API ---
pub type FARSETTINGSTYPES = i32;
pub const FST_UNKNOWN: FARSETTINGSTYPES = 0;
pub const FST_SUBKEY: FARSETTINGSTYPES = 1;
pub const FST_QWORD: FARSETTINGSTYPES = 2;
pub const FST_STRING: FARSETTINGSTYPES = 3;
pub const FST_DATA: FARSETTINGSTYPES = 4;

pub type FARSETTINGS_SUBFOLDERS = i32;
pub const FSSF_ROOT: FARSETTINGS_SUBFOLDERS = 0;
pub const FSSF_HISTORY_CMD: FARSETTINGS_SUBFOLDERS = 1;
pub const FSSF_HISTORY_FOLDER: FARSETTINGS_SUBFOLDERS = 2;
pub const FSSF_HISTORY_VIEW: FARSETTINGS_SUBFOLDERS = 3;
pub const FSSF_HISTORY_EDIT: FARSETTINGS_SUBFOLDERS = 4;
pub const FSSF_HISTORY_EXTERNAL: FARSETTINGS_SUBFOLDERS = 5;
pub const FSSF_FOLDERSHORTCUT_0: FARSETTINGS_SUBFOLDERS = 6;
pub const FSSF_FOLDERSHORTCUT_1: FARSETTINGS_SUBFOLDERS = 7;
pub const FSSF_FOLDERSHORTCUT_2: FARSETTINGS_SUBFOLDERS = 8;
pub const FSSF_FOLDERSHORTCUT_3: FARSETTINGS_SUBFOLDERS = 9;
pub const FSSF_FOLDERSHORTCUT_4: FARSETTINGS_SUBFOLDERS = 10;
pub const FSSF_FOLDERSHORTCUT_5: FARSETTINGS_SUBFOLDERS = 11;
pub const FSSF_FOLDERSHORTCUT_6: FARSETTINGS_SUBFOLDERS = 12;
pub const FSSF_FOLDERSHORTCUT_7: FARSETTINGS_SUBFOLDERS = 13;
pub const FSSF_FOLDERSHORTCUT_8: FARSETTINGS_SUBFOLDERS = 14;
pub const FSSF_FOLDERSHORTCUT_9: FARSETTINGS_SUBFOLDERS = 15;
pub const FSSF_CONFIRMATIONS: FARSETTINGS_SUBFOLDERS = 16;
pub const FSSF_SYSTEM: FARSETTINGS_SUBFOLDERS = 17;
pub const FSSF_PANEL: FARSETTINGS_SUBFOLDERS = 18;
pub const FSSF_EDITOR: FARSETTINGS_SUBFOLDERS = 19;
pub const FSSF_SCREEN: FARSETTINGS_SUBFOLDERS = 20;
pub const FSSF_DIALOG: FARSETTINGS_SUBFOLDERS = 21;
pub const FSSF_INTERFACE: FARSETTINGS_SUBFOLDERS = 22;
pub const FSSF_PANELLAYOUT: FARSETTINGS_SUBFOLDERS = 23;

pub type FAR_PLUGIN_SETTINGS_LOCATION = i32;
pub const PSL_ROAMING: FAR_PLUGIN_SETTINGS_LOCATION = 0;
pub const PSL_LOCAL: FAR_PLUGIN_SETTINGS_LOCATION = 1;

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarSettingsCreate {
    pub StructSize: usize,
    pub Guid: GUID,
    pub Handle: HANDLE,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct FarSettingsItem {
    pub StructSize: usize,
    pub Root: usize,
    pub Name: *const WCHAR,
    pub Type: FARSETTINGSTYPES,
    pub Value: FarSettingsValueData,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union FarSettingsValueData {
    pub Number: u64,
    pub String: *const WCHAR,
    pub Data: FarSettingsData,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct FarSettingsData {
    pub Size: usize,
    pub Data: *const c_void,
}

impl Default for FarSettingsValueData {
    fn default() -> Self {
        Self { Number: 0 }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarSettingsName {
    pub Name: *const WCHAR,
    pub Type: FARSETTINGSTYPES,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarSettingsHistory {
    pub Name: *const WCHAR,
    pub Param: *const WCHAR,
    pub PluginId: UUID,
    pub File: *const WCHAR,
    pub Time: FILETIME,
    pub Lock: BOOL,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarSettingsEnum {
    pub StructSize: usize,
    pub Root: usize,
    pub Count: usize,
    pub Value: FarSettingsEnumValue,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union FarSettingsEnumValue {
    pub Items: *const FarSettingsName,
    pub Histories: *const FarSettingsHistory,
}

impl Default for FarSettingsEnumValue {
    fn default() -> Self {
        Self { Items: std::ptr::null() }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarSettingsValue {
    pub StructSize: usize,
    pub Root: usize,
    pub Value: *const WCHAR,
}

// --- Viewer Structures ---
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ViewerSetMode {
    pub StructSize: usize,
    pub Type: i32, // VIEWER_SETMODE_TYPES
    pub Param: ViewerSetModeParam,
    pub Flags: VIEWER_SETMODEFLAGS_TYPES,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union ViewerSetModeParam {
    pub iParam: IntPtr,
    pub wszParam: *mut WCHAR,
}

impl Default for ViewerSetModeParam {
    fn default() -> Self {
        Self { iParam: 0 }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ViewerSelect {
    pub StructSize: usize,
    pub BlockStartPos: i64,
    pub BlockLen: i64,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ViewerSetPosition {
    pub StructSize: usize,
    pub Flags: VIEWER_SETPOS_FLAGS,
    pub StartPos: i64,
    pub LeftPos: i64,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ViewerMode {
    pub CodePage: UIntPtr,
    pub Flags: VIEWER_MODE_FLAGS,
    pub ViewMode: i32, // VIEWER_MODE_TYPE
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ViewerInfo {
    pub StructSize: usize,
    pub ViewerID: IntPtr,
    pub TabSize: IntPtr,
    pub CurMode: ViewerMode,
    pub FileSize: i64,
    pub FilePos: i64,
    pub LeftPos: i64,
    pub Options: VIEWER_OPTIONS,
    pub WindowSizeX: IntPtr,
    pub WindowSizeY: IntPtr,
}

// --- Editor Structures ---
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorSetParameter {
    pub StructSize: usize,
    pub Type: i32, // EDITOR_SETPARAMETER_TYPES
    pub Param: EditorSetParameterParam,
    pub Flags: u64,
    pub Size: usize,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union EditorSetParameterParam {
    pub iParam: IntPtr,
    pub wszParam: *mut WCHAR,
    pub Reserved: IntPtr,
}

impl Default for EditorSetParameterParam {
    fn default() -> Self {
        Self { iParam: 0 }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorUndoRedo {
    pub StructSize: usize,
    pub Command: i32, // EDITOR_UNDOREDO_COMMANDS
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorGetString {
    pub StructSize: usize,
    pub StringNumber: IntPtr,
    pub StringLength: IntPtr,
    pub StringText: *const WCHAR,
    pub StringEOL: *const WCHAR,
    pub SelStart: IntPtr,
    pub SelEnd: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorSetString {
    pub StructSize: usize,
    pub StringNumber: IntPtr,
    pub StringLength: IntPtr,
    pub StringText: *const WCHAR,
    pub StringEOL: *const WCHAR,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorInfo {
    pub StructSize: usize,
    pub EditorID: IntPtr,
    pub WindowSizeX: IntPtr,
    pub WindowSizeY: IntPtr,
    pub TotalLines: IntPtr,
    pub CurLine: IntPtr,
    pub CurPos: IntPtr,
    pub CurTabPos: IntPtr,
    pub TopScreenLine: IntPtr,
    pub LeftPos: IntPtr,
    pub Overtype: IntPtr,
    pub BlockType: IntPtr,
    pub BlockStartLine: IntPtr,
    pub Options: UIntPtr,
    pub TabSize: IntPtr,
    pub BookmarkCount: usize,
    pub SessionBookmarkCount: usize,
    pub CurState: UIntPtr,
    pub CodePage: UIntPtr,
    pub WindowArea: RECT,
    pub ClientArea: RECT,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorBookmarks {
    pub StructSize: usize,
    pub Size: usize,
    pub Count: usize,
    pub Line: *mut IntPtr,
    pub Cursor: *mut IntPtr,
    pub ScreenLine: *mut IntPtr,
    pub LeftPos: *mut IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorSetPosition {
    pub StructSize: usize,
    pub CurLine: IntPtr,
    pub CurPos: IntPtr,
    pub CurTabPos: IntPtr,
    pub TopScreenLine: IntPtr,
    pub LeftPos: IntPtr,
    pub Overtype: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorSelect {
    pub StructSize: usize,
    pub BlockType: IntPtr,
    pub BlockStartLine: IntPtr,
    pub BlockStartPos: IntPtr,
    pub BlockWidth: IntPtr,
    pub BlockHeight: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorConvertPos {
    pub StructSize: usize,
    pub StringNumber: IntPtr,
    pub SrcPos: IntPtr,
    pub DestPos: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorColor {
    pub StructSize: usize,
    pub StringNumber: IntPtr,
    pub ColorItem: IntPtr,
    pub StartPos: IntPtr,
    pub EndPos: IntPtr,
    pub Priority: UIntPtr,
    pub Flags: EDITORCOLORFLAGS,
    pub Color: FarColor,
    pub Owner: UUID,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorDeleteColor {
    pub StructSize: usize,
    pub Owner: UUID,
    pub StringNumber: IntPtr,
    pub StartPos: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorSaveFile {
    pub StructSize: usize,
    pub FileName: *const WCHAR,
    pub FileEOL: *const WCHAR,
    pub CodePage: UIntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorChange {
    pub StructSize: usize,
    pub Type: i32, // EDITOR_CHANGETYPE
    pub StringNumber: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EditorSubscribeChangeEvent {
    pub StructSize: usize,
    pub PluginId: UUID,
}

// --- RegExp & Other Structures ---
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct RegExpMatch {
    pub start: IntPtr,
    pub end: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct RegExpSearch {
    pub Text: *const WCHAR,
    pub Position: IntPtr,
    pub Length: IntPtr,
    pub Match: *mut RegExpMatch,
    pub Count: IntPtr,
    pub Reserved: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct RegExpNamedGroup {
    pub Index: usize,
    pub Name: *const WCHAR,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct RegExpStatus {
    pub StructSize: usize,
    pub Error: *const WCHAR,
    pub Position: IntPtr,
    pub Status: i32,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PanelRedrawInfo {
    pub StructSize: usize,
    pub CurrentItem: usize,
    pub TopPanelItem: usize,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct CmdLineSelect {
    pub StructSize: usize,
    pub SelStart: IntPtr,
    pub SelEnd: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarMenuItem {
    pub Flags: MENUITEMFLAGS,
    pub Text: *const WCHAR,
    pub AccelKey: FarKey,
    pub UserData: IntPtr,
    pub Reserved: [IntPtr; 2],
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarPanelDirectory {
    pub StructSize: usize,
    pub Name: *const WCHAR,
    pub Param: *const WCHAR,
    pub PluginId: UUID,
    pub File: *const WCHAR,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarGetPluginPanelItem {
    pub StructSize: usize,
    pub Size: usize,
    pub Item: *mut PluginPanelItem,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarGetDialogItem {
    pub StructSize: usize,
    pub Size: usize,
    pub Item: *mut FarDialogItem,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarDialogItemData {
    pub StructSize: usize,
    pub PtrLength: usize,
    pub PtrData: *mut WCHAR,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OpenDlgPluginData {
    pub StructSize: usize,
    pub hDlg: HANDLE,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct DialogInfo {
    pub StructSize: usize,
    pub Id: UUID,
    pub Owner: UUID,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListUpdate {
    pub StructSize: usize,
    pub Index: IntPtr,
    pub Item: FarListItem,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListInsert {
    pub StructSize: usize,
    pub Index: IntPtr,
    pub Item: FarListItem,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListGetItem {
    pub StructSize: usize,
    pub ItemIndex: IntPtr,
    pub Item: FarListItem,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListPos {
    pub StructSize: usize,
    pub SelectPos: IntPtr,
    pub TopPos: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListFind {
    pub StructSize: usize,
    pub StartIndex: IntPtr,
    pub Pattern: *const WCHAR,
    pub Flags: FARLISTFINDFLAGS,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListDelete {
    pub StructSize: usize,
    pub StartIndex: IntPtr,
    pub Count: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListInfo {
    pub StructSize: usize,
    pub Flags: FARLISTINFOFLAGS,
    pub ItemsNumber: usize,
    pub SelectPos: IntPtr,
    pub TopPos: IntPtr,
    pub MaxHeight: IntPtr,
    pub MaxLength: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListItemData {
    pub StructSize: usize,
    pub Index: IntPtr,
    pub DataSize: usize,
    pub Data: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarList {
    pub StructSize: usize,
    pub ItemsNumber: usize,
    pub Items: *mut FarListItem,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListTitles {
    pub StructSize: usize,
    pub TitleSize: usize,
    pub Title: *const WCHAR,
    pub BottomSize: usize,
    pub Bottom: *const WCHAR,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarDialogItemColors {
    pub StructSize: usize,
    pub Flags: u64,
    pub ColorsCount: usize,
    pub Colors: *mut FarColor,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FAR_CHAR_INFO {
    pub Char: WCHAR,
    pub Reserved0: WCHAR,
    pub Reserved1: i32,
    pub Attributes: FarColor,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarDialogItem {
    pub Type: FARDIALOGITEMTYPES,
    pub X1: IntPtr,
    pub Y1: IntPtr,
    pub X2: IntPtr,
    pub Y2: IntPtr,
    pub Param: FarDialogItemParam,
    pub History: *const WCHAR,
    pub Mask: *const WCHAR,
    pub Flags: FARDIALOGITEMFLAGS,
    pub Data: *const WCHAR,
    pub MaxLength: usize,
    pub UserData: IntPtr,
    pub Reserved: [IntPtr; 2],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union FarDialogItemParam {
    pub Selected: IntPtr,
    pub ListItems: *mut FarList,
    pub VBuf: *mut FAR_CHAR_INFO,
    pub Reserved0: IntPtr,
}

impl Default for FarDialogItemParam {
    fn default() -> Self {
        Self { Reserved0: 0 }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarListItem {
    pub Flags: LISTITEMFLAGS,
    pub Text: *const WCHAR,
    pub UserData: IntPtr,
    pub Reserved: IntPtr,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarGetPluginInformation {
    pub StructSize: usize,
    pub ModuleName: *const WCHAR,
    pub Flags: FAR_PLUGIN_FLAGS,
    pub PInfo: *mut PluginInfo,
    pub GInfo: *mut GlobalInfo,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarSetKeyBarTitles {
    pub StructSize: usize,
    pub Titles: *mut KeyBarTitles,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct DetectCodePageInfo {
    pub StructSize: usize,
    pub FileName: *const WCHAR,
}

// --- API Function Pointers ---
pub type FARAPIMENU = Option<unsafe extern "system" fn(PluginId: *const GUID, Id: *const GUID, X: IntPtr, Y: IntPtr, MaxHeight: IntPtr, Flags: FARMENUFLAGS, Title: *const WCHAR, Bottom: *const WCHAR, HelpTopic: *const WCHAR, BreakKeys: *const FarKey, BreakCode: *mut IntPtr, Item: *const FarMenuItem, ItemsNumber: usize) -> IntPtr>;
pub type FARAPIMESSAGE = Option<unsafe extern "system" fn(PluginId: *const GUID, Id: *const GUID, Flags: FARMESSAGEFLAGS, HelpTopic: *const WCHAR, Items: *const *const WCHAR, ItemsNumber: usize, ButtonsNumber: IntPtr) -> IntPtr>;
pub type FARAPIGETMSG = Option<unsafe extern "system" fn(PluginId: *const GUID, MsgId: IntPtr) -> *const WCHAR>;
pub type FARAPIPANELCONTROL = Option<unsafe extern "system" fn(hPanel: HANDLE, Command: FILE_CONTROL_COMMANDS, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPISAVESCREEN = Option<unsafe extern "system" fn(X1: IntPtr, Y1: IntPtr, X2: IntPtr, Y2: IntPtr) -> HANDLE>;
pub type FARAPIRESTORESCREEN = Option<unsafe extern "system" fn(hScreen: HANDLE)>;
pub type FARAPIFREESCREEN = Option<unsafe extern "system" fn(hScreen: HANDLE)>;
pub type FARAPIGETDIRLIST = Option<unsafe extern "system" fn(Dir: *const WCHAR, pPanelItem: *mut *mut PluginPanelItem, pItemsNumber: *mut usize) -> IntPtr>;
pub type FARAPIGETPLUGINDIRLIST = Option<unsafe extern "system" fn(PluginId: *const GUID, hPanel: HANDLE, Dir: *const WCHAR, pPanelItem: *mut *mut PluginPanelItem, pItemsNumber: *mut usize) -> IntPtr>;
pub type FARAPIFREEDIRLIST = Option<unsafe extern "system" fn(PanelItem: *mut PluginPanelItem, nItemsNumber: usize)>;
pub type FARAPIFREEPLUGINDIRLIST = Option<unsafe extern "system" fn(hPanel: HANDLE, PanelItem: *mut PluginPanelItem, nItemsNumber: usize)>;
pub type FARAPIVIEWER = Option<unsafe extern "system" fn(FileName: *const WCHAR, Title: *const WCHAR, X1: IntPtr, Y1: IntPtr, X2: IntPtr, Y2: IntPtr, Flags: VIEWER_FLAGS, CodePage: UIntPtr) -> IntPtr>;
pub type FARAPIEDITOR = Option<unsafe extern "system" fn(FileName: *const WCHAR, Title: *const WCHAR, X1: IntPtr, Y1: IntPtr, X2: IntPtr, Y2: IntPtr, Flags: EDITOR_FLAGS, StartLine: IntPtr, StartChar: IntPtr, CodePage: UIntPtr) -> IntPtr>;
pub type FARAPITEXT = Option<unsafe extern "system" fn(X: IntPtr, Y: IntPtr, Color: *const FarColor, Str: *const WCHAR)>;
pub type FARAPIEDITORCONTROL = Option<unsafe extern "system" fn(EditorID: IntPtr, Command: i32, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPISHOWHELP = Option<unsafe extern "system" fn(ModuleName: *const WCHAR, Topic: *const WCHAR, Flags: FARHELPFLAGS) -> BOOL>;
pub type FARAPIADVCONTROL = Option<unsafe extern "system" fn(PluginId: *const GUID, Command: ADVANCED_CONTROL_COMMANDS, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPIINPUTBOX = Option<unsafe extern "system" fn(PluginId: *const GUID, Id: *const GUID, Title: *const WCHAR, SubTitle: *const WCHAR, HistoryName: *const WCHAR, SrcText: *const WCHAR, DestText: *mut WCHAR, DestSize: usize, HelpTopic: *const WCHAR, Flags: INPUTBOXFLAGS) -> IntPtr>;
pub type FARAPICOLORDIALOG = Option<unsafe extern "system" fn(PluginId: *const GUID, Flags: u64, Color: *mut FarColor) -> BOOL>;
pub type FARAPIDIALOGINIT = Option<unsafe extern "system" fn(PluginId: *const GUID, Id: *const GUID, X1: IntPtr, Y1: IntPtr, X2: IntPtr, Y2: IntPtr, HelpTopic: *const WCHAR, Item: *const FarDialogItem, ItemsNumber: usize, Reserved: IntPtr, Flags: FARDIALOGFLAGS, DlgProc: FARWINDOWPROC, Param: *mut c_void) -> HANDLE>;
pub type FARAPIDIALOGRUN = Option<unsafe extern "system" fn(hDlg: HANDLE) -> IntPtr>;
pub type FARAPIDIALOGFREE = Option<unsafe extern "system" fn(hDlg: HANDLE)>;
pub type FARAPISENDDLGMESSAGE = Option<unsafe extern "system" fn(hDlg: HANDLE, Msg: IntPtr, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPIDEFDLGPROC = Option<unsafe extern "system" fn(hDlg: HANDLE, Msg: IntPtr, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPIVIEWERCONTROL = Option<unsafe extern "system" fn(ViewerID: IntPtr, Command: i32, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPIPLUGINSCONTROL = Option<unsafe extern "system" fn(hHandle: HANDLE, Command: i32, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPIFILEFILTERCONTROL = Option<unsafe extern "system" fn(hHandle: HANDLE, Command: i32, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPIREGEXPCONTROL = Option<unsafe extern "system" fn(hHandle: HANDLE, Command: i32, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPIMACROCONTROL = Option<unsafe extern "system" fn(PluginId: *const GUID, Command: i32, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;
pub type FARAPISETTINGSCONTROL = Option<unsafe extern "system" fn(hHandle: HANDLE, Command: i32, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;

pub type FARWINDOWPROC = Option<unsafe extern "system" fn(hDlg: HANDLE, Msg: IntPtr, Param1: IntPtr, Param2: *mut c_void) -> IntPtr>;

// Private API function types
pub type FARAPICREATEFILE = Option<unsafe extern "system" fn(Object: *const WCHAR, DesiredAccess: DWORD, ShareMode: DWORD, SecurityAttributes: LPSECURITY_ATTRIBUTES, CreationDistribution: DWORD, FlagsAndAttributes: DWORD, TemplateFile: HANDLE) -> HANDLE>;
pub type FARAPIGETFILEATTRIBUTES = Option<unsafe extern "system" fn(FileName: *const WCHAR) -> DWORD>;
pub type FARAPISETFILEATTRIBUTES = Option<unsafe extern "system" fn(FileName: *const WCHAR, dwFileAttributes: DWORD) -> BOOL>;
pub type FARAPIMOVEFILEEX = Option<unsafe extern "system" fn(ExistingFileName: *const WCHAR, NewFileName: *const WCHAR, dwFlags: DWORD) -> BOOL>;
pub type FARAPIDELETEFILE = Option<unsafe extern "system" fn(FileName: *const WCHAR) -> BOOL>;
pub type FARAPIREMOVEDIRECTORY = Option<unsafe extern "system" fn(DirName: *const WCHAR) -> BOOL>;
pub type FARAPICREATEDIRECTORY = Option<unsafe extern "system" fn(PathName: *const WCHAR, lpSecurityAttributes: LPSECURITY_ATTRIBUTES) -> BOOL>;
pub type FARAPICALLFAR = Option<unsafe extern "system" fn(CheckCode: IntPtr, Data: *mut FarMacroCall) -> IntPtr>;

// --- Standard Functions (FSF) ---
pub type FARSTDSPRINTF = *mut c_void;
pub type FARSTDSNPRINTF = *mut c_void;
pub type FARSTDSSCANF = *mut c_void;

pub type FARSTDQSORT = Option<unsafe extern "system" fn(base: *mut c_void, nelem: usize, width: usize, fcmp: Option<unsafe extern "system" fn(p1: *const c_void, p2: *const c_void, user: *mut c_void) -> i32>, userparam: *mut c_void)>;
pub type FARSTDBSEARCH = Option<unsafe extern "system" fn(key: *const c_void, base: *const c_void, nelem: usize, width: usize, fcmp: Option<unsafe extern "system" fn(p1: *const c_void, p2: *const c_void, user: *mut c_void) -> i32>, userparam: *mut c_void) -> *mut c_void>;
pub type FARSTDGETFILEOWNER = Option<unsafe extern "system" fn(Computer: *const WCHAR, Name: *const WCHAR, Owner: *mut WCHAR, Size: usize) -> usize>;
pub type FARSTDGETNUMBEROFLINKS = Option<unsafe extern "system" fn(Name: *const WCHAR) -> usize>;
pub type FARSTDATOI = Option<unsafe extern "system" fn(s: *const WCHAR) -> i32>;
pub type FARSTDATOI64 = Option<unsafe extern "system" fn(s: *const WCHAR) -> i64>;
pub type FARSTDITOA64 = Option<unsafe extern "system" fn(value: i64, Str: *mut WCHAR, radix: i32) -> *mut WCHAR>;
pub type FARSTDITOA = Option<unsafe extern "system" fn(value: i32, Str: *mut WCHAR, radix: i32) -> *mut WCHAR>;
pub type FARSTDLTRIM = Option<unsafe extern "system" fn(Str: *mut WCHAR) -> *mut WCHAR>;
pub type FARSTDRTRIM = Option<unsafe extern "system" fn(Str: *mut WCHAR) -> *mut WCHAR>;
pub type FARSTDTRIM = Option<unsafe extern "system" fn(Str: *mut WCHAR) -> *mut WCHAR>;
pub type FARSTDTRUNCSTR = Option<unsafe extern "system" fn(Str: *mut WCHAR, MaxLength: IntPtr) -> *mut WCHAR>;
pub type FARSTDTRUNCPATHSTR = Option<unsafe extern "system" fn(Str: *mut WCHAR, MaxLength: IntPtr) -> *mut WCHAR>;
pub type FARSTDQUOTESPACEONLY = Option<unsafe extern "system" fn(Str: *mut WCHAR) -> *mut WCHAR>;
pub type FARSTDPOINTTONAME = Option<unsafe extern "system" fn(Path: *const WCHAR) -> *const WCHAR>;
pub type FARSTDADDENDSLASH = Option<unsafe extern "system" fn(Path: *mut WCHAR) -> BOOL>;
pub type FARSTDCOPYTOCLIPBOARD = Option<unsafe extern "system" fn(Type: i32, Data: *const WCHAR) -> BOOL>;
pub type FARSTDPASTEFROMCLIPBOARD = Option<unsafe extern "system" fn(Type: i32, Data: *mut WCHAR, Size: usize) -> usize>;
pub type FARSTDLOCALISLOWER = Option<unsafe extern "system" fn(Ch: WCHAR) -> i32>;
pub type FARSTDLOCALISUPPER = Option<unsafe extern "system" fn(Ch: WCHAR) -> i32>;
pub type FARSTDLOCALISALPHA = Option<unsafe extern "system" fn(Ch: WCHAR) -> i32>;
pub type FARSTDLOCALISALPHANUM = Option<unsafe extern "system" fn(Ch: WCHAR) -> i32>;
pub type FARSTDLOCALUPPER = Option<unsafe extern "system" fn(LowerChar: WCHAR) -> WCHAR>;
pub type FARSTDLOCALLOWER = Option<unsafe extern "system" fn(UpperChar: WCHAR) -> WCHAR>;
pub type FARSTDLOCALUPPERBUF = Option<unsafe extern "system" fn(Buf: *mut WCHAR, Length: IntPtr)>;
pub type FARSTDLOCALLOWERBUF = Option<unsafe extern "system" fn(Buf: *mut WCHAR, Length: IntPtr)>;
pub type FARSTDLOCALSTRUPR = Option<unsafe extern "system" fn(s1: *mut WCHAR)>;
pub type FARSTDLOCALSTRLWR = Option<unsafe extern "system" fn(s1: *mut WCHAR)>;
pub type FARSTDLOCALSTRICMP = Option<unsafe extern "system" fn(s1: *const WCHAR, s2: *const WCHAR) -> i32>;
pub type FARSTDLOCALSTRNICMP = Option<unsafe extern "system" fn(s1: *const WCHAR, s2: *const WCHAR, n: IntPtr) -> i32>;
pub type FARSTDFARCLOCK = Option<unsafe extern "system" fn() -> u64>;
pub type FARSTDCOMPARESTRINGS = Option<unsafe extern "system" fn(Str1: *const WCHAR, Size1: usize, Str2: *const WCHAR, Size2: usize) -> i32>;
pub type FARSTDPROCESSNAME = Option<unsafe extern "system" fn(param1: *const WCHAR, param2: *mut WCHAR, size: usize, flags: PROCESSNAME_FLAGS) -> usize>;
pub type FARSTDUNQUOTE = Option<unsafe extern "system" fn(Str: *mut WCHAR)>;
pub type FARSTDINPUTRECORDTOKEYNAME = Option<unsafe extern "system" fn(Key: *const INPUT_RECORD, KeyText: *mut WCHAR, Size: usize) -> usize>;
pub type FARSTDXLAT = Option<unsafe extern "system" fn(Line: *mut WCHAR, StartPos: IntPtr, EndPos: IntPtr, Flags: XLAT_FLAGS) -> *mut WCHAR>;
pub type FARSTDKEYNAMETOINPUTRECORD = Option<unsafe extern "system" fn(Name: *const WCHAR, Key: *mut INPUT_RECORD) -> BOOL>;
pub type FRSUSERFUNC = Option<unsafe extern "system" fn(FData: *const PluginPanelItem, FullName: *const WCHAR, Param: *mut c_void) -> i32>;
pub type FARSTDRECURSIVESEARCH = Option<unsafe extern "system" fn(InitDir: *const WCHAR, Mask: *const WCHAR, Func: FRSUSERFUNC, Flags: FRSMODE, Param: *mut c_void)>;
pub type FARSTDMKTEMP = Option<unsafe extern "system" fn(Dest: *mut WCHAR, DestSize: usize, Prefix: *const WCHAR) -> usize>;
pub type FARSTDGETPATHROOT = Option<unsafe extern "system" fn(Path: *const WCHAR, Root: *mut WCHAR, DestSize: usize) -> usize>;
pub type FARSTDMKLINK = Option<unsafe extern "system" fn(Src: *const WCHAR, Dest: *const WCHAR, Type: LINK_TYPE, Flags: MKLINK_FLAGS) -> BOOL>;
pub type FARGETREPARSEPOINTINFO = Option<unsafe extern "system" fn(Src: *const WCHAR, Dest: *mut WCHAR, DestSize: usize) -> usize>;
pub type FARCONVERTPATH = Option<unsafe extern "system" fn(Mode: CONVERTPATHMODES, Src: *const WCHAR, Dest: *mut WCHAR, DestSize: usize) -> usize>;
pub type FARGETCURRENTDIRECTORY = Option<unsafe extern "system" fn(Size: usize, Buffer: *mut WCHAR) -> usize>;
pub type FARFORMATFILESIZE = Option<unsafe extern "system" fn(Size: u64, Width: IntPtr, Flags: FARFORMATFILESIZEFLAGS, Dest: *mut WCHAR, DestSize: usize) -> usize>;
pub type FARSTDDETECTCODEPAGE = Option<unsafe extern "system" fn(Info: *mut DetectCodePageInfo) -> UIntPtr>;

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct FarStandardFunctions {
    pub StructSize: usize,
    pub atoi: FARSTDATOI,
    pub atoi64: FARSTDATOI64,
    pub itoa: FARSTDITOA,
    pub itoa64: FARSTDITOA64,
    pub sprintf: FARSTDSPRINTF,
    pub sscanf: FARSTDSSCANF,
    pub qsort: FARSTDQSORT,
    pub bsearch: FARSTDBSEARCH,
    pub snprintf: FARSTDSNPRINTF,
    pub LIsLower: FARSTDLOCALISLOWER,
    pub LIsUpper: FARSTDLOCALISUPPER,
    pub LIsAlpha: FARSTDLOCALISALPHA,
    pub LIsAlphanum: FARSTDLOCALISALPHANUM,
    pub LUpper: FARSTDLOCALUPPER,
    pub LLower: FARSTDLOCALLOWER,
    pub LUpperBuf: FARSTDLOCALUPPERBUF,
    pub LLowerBuf: FARSTDLOCALLOWERBUF,
    pub LStrupr: FARSTDLOCALSTRUPR,
    pub LStrlwr: FARSTDLOCALSTRLWR,
    pub LStricmp: FARSTDLOCALSTRICMP,
    pub LStrnicmp: FARSTDLOCALSTRNICMP,
    pub Unquote: FARSTDUNQUOTE,
    pub LTrim: FARSTDLTRIM,
    pub RTrim: FARSTDRTRIM,
    pub Trim: FARSTDTRIM,
    pub TruncStr: FARSTDTRUNCSTR,
    pub TruncPathStr: FARSTDTRUNCPATHSTR,
    pub QuoteSpaceOnly: FARSTDQUOTESPACEONLY,
    pub PointToName: FARSTDPOINTTONAME,
    pub GetPathRoot: FARSTDGETPATHROOT,
    pub AddEndSlash: FARSTDADDENDSLASH,
    pub CopyToClipboard: FARSTDCOPYTOCLIPBOARD,
    pub PasteFromClipboard: FARSTDPASTEFROMCLIPBOARD,
    pub FarInputRecordToName: FARSTDINPUTRECORDTOKEYNAME,
    pub FarNameToInputRecord: FARSTDKEYNAMETOINPUTRECORD,
    pub XLat: FARSTDXLAT,
    pub GetFileOwner: FARSTDGETFILEOWNER,
    pub GetNumberOfLinks: FARSTDGETNUMBEROFLINKS,
    pub FarRecursiveSearch: FARSTDRECURSIVESEARCH,
    pub MkTemp: FARSTDMKTEMP,
    pub ProcessName: FARSTDPROCESSNAME,
    pub MkLink: FARSTDMKLINK,
    pub ConvertPath: FARCONVERTPATH,
    pub GetReparsePointInfo: FARGETREPARSEPOINTINFO,
    pub GetCurrentDirectory: FARGETCURRENTDIRECTORY,
    pub FormatFileSize: FARFORMATFILESIZE,
    pub FarClock: FARSTDFARCLOCK,
    pub CompareStrings: FARSTDCOMPARESTRINGS,
    pub DetectCodePage: FARSTDDETECTCODEPAGE,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PluginStartupInfo {
    pub StructSize: usize,
    pub ModuleName: *const WCHAR,
    pub Menu: FARAPIMENU,
    pub Message: FARAPIMESSAGE,
    pub GetMsg: FARAPIGETMSG,
    pub PanelControl: FARAPIPANELCONTROL,
    pub SaveScreen: FARAPISAVESCREEN,
    pub RestoreScreen: FARAPIRESTORESCREEN,
    pub GetDirList: FARAPIGETDIRLIST,
    pub GetPluginDirList: FARAPIGETPLUGINDIRLIST,
    pub FreeDirList: FARAPIFREEDIRLIST,
    pub FreePluginDirList: FARAPIFREEPLUGINDIRLIST,
    pub Viewer: FARAPIVIEWER,
    pub Editor: FARAPIEDITOR,
    pub Text: FARAPITEXT,
    pub EditorControl: FARAPIEDITORCONTROL,
    pub FSF: *mut FarStandardFunctions,
    pub ShowHelp: FARAPISHOWHELP,
    pub AdvControl: FARAPIADVCONTROL,
    pub InputBox: FARAPIINPUTBOX,
    pub ColorDialog: FARAPICOLORDIALOG,
    pub DialogInit: FARAPIDIALOGINIT,
    pub DialogRun: FARAPIDIALOGRUN,
    pub DialogFree: FARAPIDIALOGFREE,
    pub SendDlgMessage: FARAPISENDDLGMESSAGE,
    pub DefDlgProc: FARAPIDEFDLGPROC,
    pub ViewerControl: FARAPIVIEWERCONTROL,
    pub PluginsControl: FARAPIPLUGINSCONTROL,
    pub FileFilterControl: FARAPIFILEFILTERCONTROL,
    pub RegExpControl: FARAPIREGEXPCONTROL,
    pub MacroControl: FARAPIMACROCONTROL,
    pub SettingsControl: FARAPISETTINGSCONTROL,
    pub Private: *const c_void,
    pub Instance: *mut c_void,
    pub FreeScreen: FARAPIFREESCREEN,
}

// --- Helper Macros and Functions ---
#[macro_export]
macro_rules! wstr {
    ($s:expr) => {
        $crate::far::api::to_wide($s).as_ptr()
    };
}

pub fn to_wide(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}
