name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build-windows-far3:
    name: Build & Check (Windows, far3)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Run check
      run: cargo check --all-targets
      
    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings
      
    - name: Run tests
      run: cargo test
      
    - name: Build and package release
      run: .\build_release.ps1
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: far1c-windows-x64
        path: target/release/far3/
        retention-days: 14

  build-linux:
    name: Build & Check (Linux, ${{ matrix.far_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        far_version: [far2l, far2m]
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Run check
      run: cargo check --no-default-features --features ${{ matrix.far_version }} --all-targets
      
    - name: Run clippy
      run: cargo clippy --no-default-features --features ${{ matrix.far_version }} --all-targets -- -D warnings
      
    - name: Run tests
      run: cargo test --no-default-features --features ${{ matrix.far_version }}
      
    - name: Build and package release
      run: bash ./build_release.sh ${{ matrix.far_version }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: far1c-linux-${{ matrix.far_version }}-x64
        path: target/release/${{ matrix.far_version }}/
        retention-days: 14
